"""mpc_codegen.py -- QuadRotor MPC C++ generator (derives from BaseCodegen).

Emits the *prediction model* the nonlinear MPC (control-limited iLQR/DDP) needs:
the continuous dynamics f(x,u) with an external world-frame force, and its
Jacobians f_x, f_u. Unlike the FF+LQR generator it emits NO control law and NO
K_e literal -- the iLQR solver is hand-written C++ and consumes f, f_x, f_u.

Author: Diego Perazzolo, 2026.
"""
from __future__ import annotations
import sympy as sp
from base_codegen import BaseCodegen, CodegenConfig


def mpc_config(model_name="QUADROTOR_MPC_01"):
    return CodegenConfig(
        parent_namespace="CDS::Dynamics", model_name=model_name,
        state_dim=13, aug_dim=13, error_dim=12, input_dim=4,
        notebook_name="dynamics_quadRotor_MPC01.ipynb",
        state_enum_names=("X","Y","Z","Qw","Qx","Qy","Qz","VX","VY","VZ","WX","WY","WZ"),
        param_enum_names=("Mass","Ix","Iy","Iz","Gravity","DragX","DragY","DragZ",
                          "KThrust","KTorque","Arm","ThrustMax","ThrustMin"),
        param_field_names=("m","Ix","Iy","Iz","g","dx","dy","dz","kT","kQ","L","T_max","T_min"),
        param_field_comments=("vehicle mass [kg]","inertia x [kg m^2]","inertia y [kg m^2]",
            "inertia z [kg m^2]","gravity [m/s^2]","world drag x","world drag y","world drag z",
            "thrust coeff kT","torque coeff kQ","arm length [m]",
            "per-rotor thrust max [N]","per-rotor thrust min [N]"),
        param_default_values=(2.4,0.025,0.025,0.045,9.81,0.20,0.20,0.30,1e-5,1.6e-7,0.275,36.0,0.0),
        user_forces_type="std::array<double, 3>")


class MpcCodegen(BaseCodegen):
    """Nonlinear 6-DOF prediction model for MPC. InputVec = [T1..T4] (motor thrusts).
    Emits Dynamics(s,u,userF) and Jacobians(s,u) -> f_x, f_u; no control law."""

    def __init__(self, cfg=None):
        super().__init__(cfg or mpc_config())
        self._fx = None; self._fu = None

    def set_jacobians(self, fx, fu):
        self._fx = sp.Matrix(fx); self._fu = sp.Matrix(fu); return self

    def _check_ready(self):
        assert self._rhs is not None and self._fx is not None and self._fu is not None
        assert self._state_syms and self._input_syms and self._phys_syms is not None

    # ---- shared binding preamble ----
    def _bind_state_input(self, with_userf):
        SN = [str(s) for s in self._state_syms]; IN = [str(s) for s in self._input_syms]
        L = [f"    const double {n} = s[{i}];" for i, n in enumerate(SN)]
        L += [f"    const double {n} = u[{i}];" for i, n in enumerate(IN)]
        if with_userf:
            if self._uforce_syms:
                L += [f"    const double {str(s)} = userF[{i}];" for i, s in enumerate(self._uforce_syms)]
            else:
                L += ["    (void)userF;"]
        return L

    def _emit_dynamics_body(self):
        n = self.cfg.state_dim
        L = self._bind_state_input(with_userf=True)
        L += ["", "    StateVec dxdt{};"]
        L += self._emit_cse([self._rhs[i] for i in range(n)],
                            [f"dxdt[{i}]" for i in range(n)])
        L += ["    return dxdt;"]
        return "\n".join(L)

    def _emit_jacobians_body(self):
        n = self.cfg.state_dim; m = self.cfg.input_dim
        L = self._bind_state_input(with_userf=False)
        L += [""]
        exprs   = ([self._fx[i, j] for i in range(n) for j in range(n)]
                   + [self._fu[i, j] for i in range(n) for j in range(m)])
        targets = ([f"fx[{i}][{j}]" for i in range(n) for j in range(n)]
                   + [f"fu[{i}][{j}]" for i in range(n) for j in range(m)])
        L += self._emit_cse(exprs, targets)
        return "\n".join(L)

    # ---- header / source (MPC shape: no ExecuteControl, no K_e) ----
    def _emit_header(self):
        c = self.cfg; ind = c.indent
        segs = c.parent_namespace.split("::")
        ns_open = " ".join(f"namespace {s} {{" for s in segs)
        ns_close = "} "*len(segs); ns_close = ns_close.strip()+f"  // namespace {c.parent_namespace}"
        senum = "\n".join(f"{ind}{ind}{n} = {k}," for k, n in enumerate(c.state_enum_names))
        penum = "\n".join(f"{ind}{ind}{n} = {k}," for k, n in enumerate(c.param_enum_names))
        pstruct = "\n".join(f"{ind}{ind}{ind}double {f} = {d};  // {cm}"
                            for f, cm, d in zip(c.param_field_names, c.param_field_comments, c.param_default_values))
        return f'''/* {c.module_name}.hpp -- generated by {c.notebook_name}.
 * Author: {c.author}. Do not edit by hand.
 * MPC prediction model: dynamics f(x,u) + Jacobians f_x, f_u. No control law.
 */
#pragma once
#include <array>
#include <cstddef>

{ns_open}

class {c.model_name} {{
public:
{ind}static constexpr std::size_t STATE_DIM = {c.state_dim};
{ind}static constexpr std::size_t INPUT_DIM = {c.input_dim};
{ind}using StateVec   = std::array<double, STATE_DIM>;
{ind}using InputVec   = std::array<double, INPUT_DIM>;
{ind}using UserForces = {c.user_forces_type};

{ind}enum class StateName : std::size_t {{
{senum}
{ind}}};
{ind}enum class ParamName : std::size_t {{
{penum}
{ind}}};

{ind}{c.model_name}();

{ind}// State derivative dx/dt = f(x, u) + world-frame external force userF.
{ind}StateVec Dynamics(const StateVec& s, const InputVec& u, const UserForces& userF) const;
{ind}// Jacobians of f at (x,u): fx = df/dx (STATE x STATE), fu = df/du (STATE x INPUT).
{ind}// userF is additive, so it does not enter the Jacobians.
{ind}void Jacobians(const StateVec& s, const InputVec& u,
{ind}               double fx[STATE_DIM][STATE_DIM], double fu[STATE_DIM][INPUT_DIM]) const;

{ind}static double GetState(const StateVec& s, StateName n);
{ind}static void   SetState(StateVec& s, StateName n, double v);
{ind}double GetParam(ParamName n) const;
{ind}void   SetParam(ParamName n, double v);
{ind}static constexpr std::size_t StateToIdx(StateName n) noexcept {{ return static_cast<std::size_t>(n); }}

private:
{ind}struct PhysicsParams {{
{pstruct}
{ind}}};
{ind}PhysicsParams m_p;
}};

{ns_close}
'''

    def _emit_source(self):
        c = self.cfg; ind = c.indent; cls = c.model_name
        segs = c.parent_namespace.split("::")
        ns_open = " ".join(f"namespace {s} {{" for s in segs)
        ns_close = "} "*len(segs); ns_close = ns_close.strip()+f"  // namespace {c.parent_namespace}"
        gs = "\n".join(f"{ind}{ind}case StateName::{n}: return s[{k}];" for k, n in enumerate(c.state_enum_names))
        ss = "\n".join(f"{ind}{ind}case StateName::{n}: s[{k}] = v; return;" for k, n in enumerate(c.state_enum_names))
        gp = "\n".join(f"{ind}{ind}case ParamName::{e}: return m_p.{f};" for e, f in zip(c.param_enum_names, c.param_field_names))
        sp_ = "\n".join(f"{ind}{ind}case ParamName::{e}: m_p.{f} = v; return;" for e, f in zip(c.param_enum_names, c.param_field_names))
        dyn_sig = (f"{cls}::StateVec {cls}::Dynamics(const StateVec& s, const InputVec& u,\n"
                   f"{' '*(len('StateVec')+len(cls)+len('Dynamics')+4)}const UserForces& userF) const")
        jac_sig = (f"void {cls}::Jacobians(const StateVec& s, const InputVec& u,\n"
                   f"{' '*(len('void')+len(cls)+len('Jacobians')+3)}double fx[STATE_DIM][STATE_DIM], "
                   f"double fu[STATE_DIM][INPUT_DIM]) const")
        return f'''/* {c.module_name}.cpp -- generated by {c.notebook_name}.
 * Author: {c.author}. Do not edit by hand.
 */
#include "{c.module_name}.hpp"
#include <cmath>

{ns_open}

{cls}::{cls}() = default;

double {cls}::GetState(const StateVec& s, StateName n) {{
{ind}switch (n) {{
{gs}
{ind}}}
{ind}return 0.0;
}}
void {cls}::SetState(StateVec& s, StateName n, double v) {{
{ind}switch (n) {{
{ss}
{ind}}}
}}
double {cls}::GetParam(ParamName n) const {{
{ind}switch (n) {{
{gp}
{ind}}}
{ind}return 0.0;
}}
void {cls}::SetParam(ParamName n, double v) {{
{ind}switch (n) {{
{sp_}
{ind}}}
}}

{dyn_sig}
{{
{self._emit_dynamics_body()}
}}

{jac_sig}
{{
{self._emit_jacobians_body()}
}}

{ns_close}
'''
