/* dynamics_ff_lqr_01.hpp -- generated by 01_model_derivation.ipynb.
 * Author: Diego Perazzolo. Do not edit by hand.
 */
#pragma once

#include <array>
#include <cstddef>

#include "core_defs.hpp"

namespace CDS { namespace Dynamics {

class FF_LQR_01 {
public:
    using StateVec = std::array<double, 15>;
    using InputVec = std::array<double, 4>;

    // Public name enums for state and parameter accessors.
    // Internal indices and the parameter struct layout are private to the .cpp.
    enum class StateName : std::size_t {
        X = 0,
        Y = 1,
        Z = 2,
        Alpha = 3,
        Beta = 4,
        Psi = 5,
        XDot = 6,
        YDot = 7,
        ZDot = 8,
        AlphaDot = 9,
        BetaDot = 10,
        PsiDot = 11,
        IntX = 12,
        IntY = 13,
        IntZ = 14,
    };

    enum class ParamName : std::size_t {
        Mass = 0,
        Ix = 1,
        Iy = 2,
        Iz = 3,
        Gravity = 4,
        DragLateral = 5,
        DragAxial = 6,
        ThrustMax = 7,
    };

    FF_LQR_01();

    // ----- Control -----
    // u = u_ff(reference) + u_lqr(state), with F1 saturated to [0, F1_max].
    InputVec ExecuteControl(const StateVec& s, const Reference_t& r) const;

    // ----- Dynamics -----
    // dxdt = f(s, u, ref_pos, userF). Augmented integrators use ref_pos only.
    StateVec Dynamics(const StateVec& s,
                      const InputVec& u,
                      const Reference_t& ref,
                      const Vec3& userF) const;

    // ----- Accessors -----
    static double GetState(const StateVec& s, StateName n);
    static void   SetState(StateVec& s, StateName n, double v);
    double GetParam(ParamName n) const;
    void   SetParam(ParamName n, double v);

    // Convert a StateName to its array index. Use this everywhere instead of
    // raw static_cast<std::size_t> to keep call sites readable.
    static constexpr std::size_t StateToIdx(StateName n) noexcept {
        return static_cast<std::size_t>(n);
    }

private:
    struct PhysicsParams {
            double m = 10.0;  // vehicle mass [kg]
            double Ix = 3.3333333333333335;  // inertia around body x [kg m^2]
            double Iy = 3.3333333333333335;  // inertia around body y [kg m^2]
            double Iz = 1.0;  // inertia around body z [kg m^2]
            double g = 9.81;  // gravity [m/s^2]
            double c = 1.0;  // lateral drag coeff (body x, y) [N s/m]
            double cz = 0.02;  // axial drag coeff (body z) [N s/m]
            double F1_max = 700.0;  // thrust upper saturation [N]
    };

    PhysicsParams m_p;
};

} }  // namespace CDS::Dynamics
