/* dynamics_ff_lqr_01.cpp -- generated by 01_model_derivation.ipynb.
 * Author: Diego Perazzolo. Do not edit by hand.
 */
#include "dynamics_ff_lqr_01.hpp"

#include <cmath>

namespace CDS { namespace Dynamics {

namespace {
    // LQR augmented gain matrix. Row i = gains for input u[i].
    static constexpr std::array<std::array<double, 15>, 4> K_e = {{
        {{ -9.473030436060591091e-15, 4.971323259741968030e-16, 3.953120887042830844e+01, -1.658611779951683237e-14, 1.049856741317867734e-14, 9.115166648894372265e-20, -5.743521935285377868e-15, -2.665480057398528492e-16, 2.811582373787139488e+01, -8.790929960032375101e-16, 2.830171275596240560e-15, -3.847772625665432055e-20, 2.354725662972446723e-15, 6.721059078437195320e-15, -9.999999999999992895e+00 }},
        {{ 4.194782617982674822e+01, 4.679544678980609893e-14, -1.815154911684523544e-15, 1.750834812839657104e+02, -1.458916308968266243e-13, 7.289498798221232611e-14, 3.619626109343095521e+01, 2.852670366886705177e-14, -2.637278988009712136e-15, 4.655344464762813317e+01, 5.169086328434727614e-15, -7.214405721221319581e-15, -1.000000000000001066e+01, -8.906336799041390493e-15, -3.846203234163202848e-16 }},
        {{ 1.887797444826613768e-13, -4.194782617982704664e+01, 3.145011495297660025e-14, 2.488537743018944526e-13, 1.750834812839652557e+02, 2.455206440720302032e-14, 1.088134384415194456e-13, -3.619626109343107601e+01, 8.490513826788721680e-15, 5.169086328434727614e-15, 4.655344464762812606e+01, -6.342946042144703928e-15, -4.507751536383623188e-14, 1.000000000000009237e+01, -8.426888283655109957e-15 }},
        {{ -1.537231564522373342e-13, 3.172886004915302471e-14, 1.471365882096264164e-18, -3.640021139846792100e-13, -1.643457869943794823e-13, 3.162277660168388849e+01, -1.157507519810773624e-13, 3.417121528449758316e-14, -3.847772625665431934e-19, -2.404801907073773404e-14, -2.114315347381567976e-14, 3.260744628460462025e+01, 3.608281461057490196e-14, -4.878741829764852927e-15, -3.815252115626924496e-19 }}
    }};
} // anonymous namespace

FF_LQR_01::FF_LQR_01() = default;

// =============================================================================
// Accessors
// =============================================================================
double FF_LQR_01::GetState(const StateVec& s, StateName n) {
    switch (n) {
        case StateName::X: return s[0];
        case StateName::Y: return s[1];
        case StateName::Z: return s[2];
        case StateName::Alpha: return s[3];
        case StateName::Beta: return s[4];
        case StateName::Psi: return s[5];
        case StateName::XDot: return s[6];
        case StateName::YDot: return s[7];
        case StateName::ZDot: return s[8];
        case StateName::AlphaDot: return s[9];
        case StateName::BetaDot: return s[10];
        case StateName::PsiDot: return s[11];
        case StateName::IntX: return s[12];
        case StateName::IntY: return s[13];
        case StateName::IntZ: return s[14];
    }
    return 0.0;
}

void FF_LQR_01::SetState(StateVec& s, StateName n, double v) {
    switch (n) {
        case StateName::X: s[0] = v; return;
        case StateName::Y: s[1] = v; return;
        case StateName::Z: s[2] = v; return;
        case StateName::Alpha: s[3] = v; return;
        case StateName::Beta: s[4] = v; return;
        case StateName::Psi: s[5] = v; return;
        case StateName::XDot: s[6] = v; return;
        case StateName::YDot: s[7] = v; return;
        case StateName::ZDot: s[8] = v; return;
        case StateName::AlphaDot: s[9] = v; return;
        case StateName::BetaDot: s[10] = v; return;
        case StateName::PsiDot: s[11] = v; return;
        case StateName::IntX: s[12] = v; return;
        case StateName::IntY: s[13] = v; return;
        case StateName::IntZ: s[14] = v; return;
    }
}

double FF_LQR_01::GetParam(ParamName n) const {
    switch (n) {
        case ParamName::Mass: return m_p.m;
        case ParamName::Ix: return m_p.Ix;
        case ParamName::Iy: return m_p.Iy;
        case ParamName::Iz: return m_p.Iz;
        case ParamName::Gravity: return m_p.g;
        case ParamName::DragLateral: return m_p.c;
        case ParamName::DragAxial: return m_p.cz;
        case ParamName::ThrustMax: return m_p.F1_max;
    }
    return 0.0;
}

void FF_LQR_01::SetParam(ParamName n, double v) {
    switch (n) {
        case ParamName::Mass: m_p.m = v; return;
        case ParamName::Ix: m_p.Ix = v; return;
        case ParamName::Iy: m_p.Iy = v; return;
        case ParamName::Iz: m_p.Iz = v; return;
        case ParamName::Gravity: m_p.g = v; return;
        case ParamName::DragLateral: m_p.c = v; return;
        case ParamName::DragAxial: m_p.cz = v; return;
        case ParamName::ThrustMax: m_p.F1_max = v; return;
    }
}

// =============================================================================
// Dynamics: dxdt = f(s, u, ref_pos, userF).
// =============================================================================
FF_LQR_01::StateVec FF_LQR_01::Dynamics(const StateVec& s,
                             const InputVec& u,
                             const Reference_t& ref,
                             const Vec3& userF) const
{
    using SN = StateName;
    StateVec dxdt{};
    const Vec3 ref_pos = {ref.pos};

    // Precompute attitude trig (used multiple times below).
    const double sa  = std::sin(s[StateToIdx(SN::Alpha)]);
    const double ca  = std::cos(s[StateToIdx(SN::Alpha)]);
    const double sb  = std::sin(s[StateToIdx(SN::Beta)]);
    const double cb  = std::cos(s[StateToIdx(SN::Beta)]);

    // State and input aliases.
    const double xd = s[StateToIdx(SN::XDot)];
    const double yd = s[StateToIdx(SN::YDot)];
    const double zd = s[StateToIdx(SN::ZDot)];
    const double F1 = u[0];
    const double T1 = u[1];
    const double T2 = u[2];
    const double T3 = u[3];

    // Kinematics: dp/dt = v, dangles/dt = omega.
    dxdt[StateToIdx(SN::X)] = s[StateToIdx(SN::XDot)];
    dxdt[StateToIdx(SN::Y)] = s[StateToIdx(SN::YDot)];
    dxdt[StateToIdx(SN::Z)] = s[StateToIdx(SN::ZDot)];
    dxdt[StateToIdx(SN::Alpha)] = s[StateToIdx(SN::AlphaDot)];
    dxdt[StateToIdx(SN::Beta)] = s[StateToIdx(SN::BetaDot)];
    dxdt[StateToIdx(SN::Psi)] = s[StateToIdx(SN::PsiDot)];

    // Translational dynamics: dv/dt = (F_thrust + F_gravity + F_drag) / m.
    dxdt[StateToIdx(SN::XDot)] = F1*cb*sa/m_p.m + xd*(-m_p.c*ca*ca*cb*cb/m_p.m + m_p.c*cb*cb/m_p.m - m_p.c/m_p.m + m_p.cz*ca*ca*cb*cb/m_p.m - m_p.cz*cb*cb/m_p.m) + yd*(-m_p.c*cb*sa*sb/m_p.m + m_p.cz*cb*sa*sb/m_p.m) + zd*(m_p.c*ca*cb*cb*sa/m_p.m - m_p.cz*ca*cb*cb*sa/m_p.m);
    dxdt[StateToIdx(SN::YDot)] = -F1*sb/m_p.m + xd*(-m_p.c*cb*sa*sb/m_p.m + m_p.cz*cb*sa*sb/m_p.m) + yd*(-m_p.c*cb*cb/m_p.m + m_p.cz*cb*cb/m_p.m - m_p.cz/m_p.m) + zd*(-m_p.c*ca*cb*sb/m_p.m + m_p.cz*ca*cb*sb/m_p.m);
    dxdt[StateToIdx(SN::ZDot)] = F1*ca*cb/m_p.m - m_p.g + xd*(m_p.c*ca*cb*cb*sa/m_p.m - m_p.cz*ca*cb*cb*sa/m_p.m) + yd*(-m_p.c*ca*cb*sb/m_p.m + m_p.cz*ca*cb*sb/m_p.m) + zd*(m_p.c*ca*ca*cb*cb/m_p.m - m_p.c/m_p.m - m_p.cz*ca*ca*cb*cb/m_p.m);

    // User-input forces in inertial frame, divided by mass.
    dxdt[StateToIdx(SN::XDot)] += userF[0] / m_p.m;
    dxdt[StateToIdx(SN::YDot)] += userF[1] / m_p.m;
    dxdt[StateToIdx(SN::ZDot)] += userF[2] / m_p.m;

    // Rotational dynamics: I diagonal, torques are direct inputs.
    dxdt[StateToIdx(SN::AlphaDot)] = T1 / m_p.Ix;
    dxdt[StateToIdx(SN::BetaDot)]  = T2 / m_p.Iy;
    dxdt[StateToIdx(SN::PsiDot)]   = T3 / m_p.Iz;

    // Augmented states: integral of position tracking error.
    dxdt[StateToIdx(SN::IntX)] = ref_pos[0] - s[StateToIdx(SN::X)];
    dxdt[StateToIdx(SN::IntY)] = ref_pos[1] - s[StateToIdx(SN::Y)];
    dxdt[StateToIdx(SN::IntZ)] = ref_pos[2] - s[StateToIdx(SN::Z)];

    return dxdt;
}

// =============================================================================
// ExecuteControl: u = u_ff(r) + u_lqr(s), F1 saturated to [0, F1_max].
// =============================================================================
FF_LQR_01::InputVec FF_LQR_01::ExecuteControl(const StateVec& s,
                                   const Reference_t& r) const
{
    // Pull reference derivatives into named locals for clarity.
    const double ax = r.acc[0], ay = r.acc[1], az = r.acc[2];
    const double jx = r.jerk[0], jy = r.jerk[1], jz = r.jerk[2];
    const double sx = r.snap[0], sy = r.snap[1], sz = r.snap[2];

    // Feedforward thrust magnitude and tilt angles from desired acceleration.
    const double F1_ff    = m_p.m*std::sqrt(ax*ax + ay*ay + std::pow(az + m_p.g, 2));
    const double alpha_ff = std::atan2(ax, az + m_p.g);
    const double beta_ff  = std::atan2(-ay, std::sqrt(ax*ax + std::pow(az + m_p.g, 2)));
    // alpha_ff/beta_ff are exposed for diagnostic/attitude-FF use; they are not consumed below.
    (void)alpha_ff; (void)beta_ff;

    // Torque feedforward: from second derivatives of FF angles (needs jerk and snap of the reference).
    const double T1_ff    = m_p.Ix*(2.0*ax*jz*(ax*jx + jz*(az + m_p.g)) - 2.0*jx*(az + m_p.g)*(ax*jx + jz*(az + m_p.g)) + (ax*ax + std::pow(az + m_p.g, 2))*(-ax*sz + sx*(az + m_p.g)))/std::pow(ax*ax + std::pow(az + m_p.g, 2), 2);
    const double T2_ff    = -m_p.Iy*std::pow(ax*ax + std::pow(az + m_p.g, 2), -1.5)*(2.0*ay*(ax*ax + std::pow(az + m_p.g, 2))*(ax*jx + jz*(az + m_p.g))*(ax*jx + ay*jy + jz*(az + m_p.g)) - ay*(ax*ax + std::pow(az + m_p.g, 2))*(ax*ax + ay*ay + std::pow(az + m_p.g, 2))*(ax*sx + jx*jx + jz*jz + sz*(az + m_p.g)) + ay*std::pow(ax*jx + jz*(az + m_p.g), 2)*(ax*ax + ay*ay + std::pow(az + m_p.g, 2)) - 2.0*jy*std::pow(ax*ax + std::pow(az + m_p.g, 2), 2)*(ax*jx + ay*jy + jz*(az + m_p.g)) + sy*std::pow(ax*ax + std::pow(az + m_p.g, 2), 2)*(ax*ax + ay*ay + std::pow(az + m_p.g, 2)))/std::pow(ax*ax + ay*ay + std::pow(az + m_p.g, 2), 2);
    // Roll FF is zero by design (psi held at zero).
    const double T3_ff    = 0.0;

    // Costruisci s_ref minimale dal Reference (versione "good enough")
    StateVec s_ref = {};
    s_ref[0] = r.pos[0];   // X
    s_ref[1] = r.pos[1];   // Y
    s_ref[2] = r.pos[2];   // Z
    s_ref[3] = alpha_ff;   // Alpha (già calcolato sopra in ExecuteControl)
    s_ref[4] = beta_ff;    // Beta
    s_ref[5] = 0.0;        // Psi
    s_ref[6] = r.vel[0];   // XDot
    s_ref[7] = r.vel[1];   // YDot
    s_ref[8] = r.vel[2];   // ZDot
    // s_ref[9..14] restano 0 (angular velocity FF e integrators)

    InputVec u_lqr{};
    for (size_t i = 0; i < 4; ++i) {
        double v = 0.0;
        for (size_t j = 0; j < 15; ++j) {
            v += K_e[i][j] * (s[j] - s_ref[j]);
        }
        u_lqr[i] = -v;
    }

    // Total control: u = u_ff + u_lqr, then saturate F1.
    InputVec u{};
    u[0] = F1_ff + u_lqr[0];
    u[1] = T1_ff + u_lqr[1];
    u[2] = T2_ff + u_lqr[2];
    u[3] = T3_ff + u_lqr[3];

    if      (u[0] > m_p.F1_max) u[0] = m_p.F1_max;
    else if (u[0] < 0.0)        u[0] = 0.0;

    return u;
}

} }  // namespace CDS::Dynamics
