// =============================================================================
// Controlled Descent Simulator
// =============================================================================
//
// Copyright (c) 2026 Diego Perazzolo
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//
// =============================================================================
// File        : dispatch.cpp
// Description : ws_protocol request dispatcher — see dispatch.hpp.
// Author      : Diego Perazzolo
// Created     : 2026
// GENERATED by apps/common/gen_ext.py from apps/common/ext_api.py — DO NOT EDIT BY HAND
// =============================================================================

#include "dispatch.hpp"

#include <cstdio>
#include <cstring>

#include "ext_comm.hpp"
#include "ws_protocol.hpp"

using namespace ws_proto;

/* Static functions */

/* Copy a wire request into its typed struct, returns true on size mismatch */
template <typename Req>
static bool _parse(const std::vector<uint8_t>& msg, Req& req)
{
    if(msg.size() != sizeof(Req))
    {
        // Err: malformed request
        return true;
    }
    memcpy(&req, msg.data(), sizeof(Req));
    return false;
}

template <typename Resp>
static std::vector<uint8_t> _serialize(const Resp& resp)
{
    std::vector<uint8_t> out(sizeof(Resp));
    memcpy(out.data(), &resp, sizeof(Resp));
    return out;
}

static std::vector<uint8_t> _respBool(const header_t& h, bool isError)
{
    respBool_t resp = {};
    resp.h = h;
    resp.isError = isError ? 1 : 0;
    return _serialize(resp);
}

/* Dispatch one request to the ext communication layer */
std::vector<uint8_t> server_dispatch(const std::vector<uint8_t>& msg)
{
    if(msg.size() < sizeof(header_t))
    {
        // Err: too short to carry a header, no way to answer meaningfully
        return {};
    }

    header_t h = {};
    memcpy(&h, msg.data(), sizeof(header_t));

    if(h.version != WS_PROTOCOL_VERSION)
    {
        // Err: client generated from a different API description
        printf("[cds-server] protocol version mismatch: client 0x%02X, server 0x%02X\n",
               (unsigned)h.version, (unsigned)WS_PROTOCOL_VERSION);
        h.version = WS_PROTOCOL_VERSION; // answer with ours, the client rejects it
        return _respBool(h, true);
    }

    switch(h.type)
    {
        case WS_MSG_INIT_ROCKET:
        {
            reqInitRocket_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            printf("[cds-server] init rocket\n");
            return _respBool(h, ext_initRocket_FFLQR01(req.p));
        }

        case WS_MSG_INIT_QUAD_ROTOR:
        {
            reqInitQuadRotor_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            printf("[cds-server] init quadrotor\n");
            return _respBool(h, ext_initQuadRotor_FFLQR01(req.p));
        }

        case WS_MSG_TRAJ_GET_REF:
        {
            reqTrajGetRef_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            ext_trajectoryReference ret = ext_trajectory_get_reference(req.t);

            respTrajGetRef_t resp = {};
            resp.h = h;
            resp.pos = ret.pos;
            resp.yaw = ret.yaw;
            resp.vel = ret.vel;
            resp.yawRate = ret.yawRate;
            resp.acc = ret.acc;
            resp.yawAcc = ret.yawAcc;
            resp.isError = ret.isError ? 1 : 0;
            return _serialize(resp);
        }

        case WS_MSG_TRAJ_APPEND_POLY4:
        {
            reqTrajAppendPoly4_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            return _respBool(h, ext_trajectory_append_poly4(req.p));
        }

        case WS_MSG_TRAJ_APPEND_POINT:
        {
            reqTrajAppendPoint_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            return _respBool(h, ext_trajectory_append_point(req.p));
        }

        case WS_MSG_TRAJ_REMOVE_LAST:
        {
            reqTrajRemoveLast_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            return _respBool(h, ext_trajectory_remove_last_item());
        }

        case WS_MSG_SET_SYSTEM_PARAMS:
        {
            reqSetSystemParams_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            return _respBool(h, ext_setSystemParams(req.p));
        }

        case WS_MSG_GET_SNAPSHOT:
        {
            reqGetSnapshot_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            ext_snapshotData ret = ext_getSnapshot();

            respGetSnapshot_t resp = {};
            resp.h = h;
            resp.time_seconds = ret.time_seconds;
            resp.state = ret.state;
            resp.err = ret.err;
            resp.isError = ret.isError ? 1 : 0;
            return _serialize(resp);
        }

        case WS_MSG_RUN:
        {
            reqRun_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            return _respBool(h, ext_run());
        }

        case WS_MSG_STOP:
        {
            reqStop_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            return _respBool(h, ext_stop());
        }

        case WS_MSG_GET_PLANT_SNAPSHOT:
        {
            reqGetPlantSnapshot_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            ext_plantSnapshotData ret = ext_getPlantSnapshot();

            respGetPlantSnapshot_t resp = {};
            resp.h = h;
            resp.time_seconds = ret.time_seconds;
            resp.sequence = ret.sequence;
            resp.state = ret.state;
            resp.isAttached = ret.isAttached ? 1 : 0;
            resp.isReadyToStart = ret.isReadyToStart ? 1 : 0;
            resp.isError = ret.isError ? 1 : 0;
            return _serialize(resp);
        }

        case WS_MSG_BEGIN_STAGING:
        {
            reqBeginStaging_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            printf("[cds-server] begin staging\n");
            return _respBool(h, ext_beginStaging(req.safetyAltitude));
        }

        case WS_MSG_STOP_STAGING:
        {
            reqStopStaging_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            printf("[cds-server] stop staging\n");
            return _respBool(h, ext_stopStaging());
        }

        case WS_MSG_INIT_QUAD_ROTOR_MPC:
        {
            reqInitQuadRotorMPC_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            printf("[cds-server] init quadrotor mpc\n");
            return _respBool(h, ext_initQuadRotor_MPC01(req.p));
        }

        case WS_MSG_GET_LOG_BATCH:
        {
            reqGetLogBatch_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            respGetLogBatch_t resp = {};
            resp.h = h;
            resp.p = ext_getLogBatch();
            return _serialize(resp);
        }

        case WS_MSG_GET_LOG_MODULES:
        {
            reqGetLogModules_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            respGetLogModules_t resp = {};
            resp.h = h;
            resp.p = ext_getLogModules();
            return _serialize(resp);
        }

        case WS_MSG_SET_LOG_LEVEL:
        {
            reqSetLogLevel_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            return _respBool(h, ext_setLogLevel(req.p));
        }

        case WS_MSG_GET_PROFILER_MODULES:
        {
            reqGetProfilerModules_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            respGetProfilerModules_t resp = {};
            resp.h = h;
            resp.p = ext_getProfilerModules();
            return _serialize(resp);
        }

        case WS_MSG_SET_PROFILER_ENABLED:
        {
            reqSetProfilerEnabled_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            ext_profilerEnableParams par = {};
            par.module = req.module;
            par.enabled = req.enabled != 0;

            return _respBool(h, ext_setProfilerEnabled(par));
        }

        case WS_MSG_GET_PROFILER_TABLE:
        {
            reqGetProfilerTable_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            respGetProfilerTable_t resp = {};
            resp.h = h;
            resp.p = ext_getProfilerTable();
            return _serialize(resp);
        }

        case WS_MSG_RESET_PROFILER:
        {
            reqResetProfiler_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            return _respBool(h, ext_resetProfiler());
        }

        case WS_MSG_SET_DIAG_FILES:
        {
            reqSetDiagFiles_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            ext_diagFiles par = {};
            par.logFile = req.logFile != 0;
            par.profileRaw = req.profileRaw != 0;

            return _respBool(h, ext_setDiagFiles(par));
        }

        case WS_MSG_SET_RECORDING:
        {
            reqSetRecording_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            printf("[cds-server] set recording\n");
            ext_recordParams par = {};
            par.enabled = req.enabled != 0;

            respSetRecording_t resp = {};
            resp.h = h;
            resp.p = ext_setRecording(par);
            return _serialize(resp);
        }

        case WS_MSG_GET_RECORD_STATUS:
        {
            reqGetRecordStatus_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            respGetRecordStatus_t resp = {};
            resp.h = h;
            resp.p = ext_getRecordStatus();
            return _serialize(resp);
        }

        case WS_MSG_INIT_ROCKET_MPC:
        {
            reqInitRocketMPC_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            printf("[cds-server] init rocket mpc\n");
            return _respBool(h, ext_initRocket_MPC01(req.p));
        }

        case WS_MSG_MODEL_GET_MANIFEST:
        {
            reqModelGetManifest_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            respModelGetManifest_t resp = {};
            resp.h = h;
            resp.p = ext_modelGetManifest();
            return _serialize(resp);
        }

        case WS_MSG_MODEL_SET_PARAM:
        {
            reqModelSetParam_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            printf("[cds-server] set model param\n");
            return _respBool(h, ext_modelSetParam(req.p));
        }

        case WS_MSG_CONTROLLER_GET_MANIFEST:
        {
            reqControllerGetManifest_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            respControllerGetManifest_t resp = {};
            resp.h = h;
            resp.p = ext_controllerGetManifest();
            return _serialize(resp);
        }

        case WS_MSG_CONTROLLER_SET_PARAM:
        {
            reqControllerSetParam_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            printf("[cds-server] set controller param\n");
            return _respBool(h, ext_controllerSetParam(req.p));
        }

        case WS_MSG_OBSERVER_GET_MANIFEST:
        {
            reqObserverGetManifest_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            respObserverGetManifest_t resp = {};
            resp.h = h;
            resp.p = ext_observerGetManifest();
            return _serialize(resp);
        }

        case WS_MSG_OBSERVER_SET_PARAM:
        {
            reqObserverSetParam_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            printf("[cds-server] set observer param\n");
            return _respBool(h, ext_observerSetParam(req.p));
        }

        case WS_MSG_SENSOR_GET_MANIFEST:
        {
            reqSensorGetManifest_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            respSensorGetManifest_t resp = {};
            resp.h = h;
            resp.p = ext_sensorGetManifest();
            return _serialize(resp);
        }

        case WS_MSG_SENSOR_SET_PARAM:
        {
            reqSensorSetParam_t req = {};
            if(_parse(msg, req)) return _respBool(h, true);

            printf("[cds-server] set sensor param\n");
            return _respBool(h, ext_sensorSetParam(req.p));
        }

        default:
            // Err: unknown message type
            return _respBool(h, true);
    }
}
