// =============================================================================
// Controlled Descent Simulator
// =============================================================================
//
// Copyright (c) 2026 Diego Perazzolo
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//
// =============================================================================
// File        : ext_comm_ws.cpp
// Description : WebSocket adapter of the external communication API.
//               Drop-in replacement for ext_comm.cpp: instead of calling the
//               core directly, every ext_* call is marshalled into a
//               ws_protocol message and round-tripped through the libs/ws
//               synchronous RPC transport (ws_rpc_client) to a native server
//               running the core. See ws_rpc_client.hpp for the transport
//               requirements (COOP/COEP, bridge worker) and URL selection.
// Author      : Diego Perazzolo
// Created     : 2026
// GENERATED by apps/common/gen_ext.py from apps/common/ext_api.py — DO NOT EDIT BY HAND
// =============================================================================

#include <cstdint>
#include "ext_comm.hpp"
#include "ws_protocol.hpp"
#include "ws_rpc_client.hpp"

using namespace ws_proto;

/* Static functions */

/* Round-trips one request/response pair, returns true on error */
template <typename Req, typename Resp>
static bool _rpc(Req& req, Resp& resp)
{
    req.h.version = WS_PROTOCOL_VERSION;

    int n = ws_rpc(reinterpret_cast<const uint8_t*>(&req), sizeof(Req),
                   reinterpret_cast<uint8_t*>(&resp), sizeof(Resp));

    if(n != (int)sizeof(Resp))
    {
        // Err: transport failure or unexpected response size
        return true;
    }

    if(resp.h.version != WS_PROTOCOL_VERSION)
    {
        // Err: the server was generated from a different API description
        return true;
    }

    if(resp.h.type != req.h.type)
    {
        // Err: response does not match the request
        return true;
    }

    return false;
}

/* ext functions */

bool ext_initRocket_FFLQR01(ext_initRocketParams params)
{
    reqInitRocket_t req = {};
    respBool_t resp = {};

    req.h.type = WS_MSG_INIT_ROCKET;
    req.p = params;

    if(_rpc(req, resp))
    {
        return true;
    }

    return resp.isError != 0;
}

bool ext_initQuadRotor_FFLQR01(ext_initQuadRotorParams params)
{
    reqInitQuadRotor_t req = {};
    respBool_t resp = {};

    req.h.type = WS_MSG_INIT_QUAD_ROTOR;
    req.p = params;

    if(_rpc(req, resp))
    {
        return true;
    }

    return resp.isError != 0;
}

ext_trajectoryPoint ext_trajectory_get_point(ext_coord_t t)
{
    reqTrajGetPoint_t req = {};
    respTrajGetPoint_t resp = {};

    req.h.type = WS_MSG_TRAJ_GET_POINT;
    req.t = t;

    if(_rpc(req, resp))
    {
        // Err
        return {};
    }

    return resp.p;
}

bool ext_trajectory_append_poly4(ext_trajectoryPoly4Params_t params)
{
    reqTrajAppendPoly4_t req = {};
    respBool_t resp = {};

    req.h.type = WS_MSG_TRAJ_APPEND_POLY4;
    req.p = params;

    if(_rpc(req, resp))
    {
        return true;
    }

    return resp.isError != 0;
}

bool ext_trajectory_append_point(ext_trajectoryPointParams_t params)
{
    reqTrajAppendPoint_t req = {};
    respBool_t resp = {};

    req.h.type = WS_MSG_TRAJ_APPEND_POINT;
    req.p = params;

    if(_rpc(req, resp))
    {
        return true;
    }

    return resp.isError != 0;
}

bool ext_trajectory_remove_last_item(void)
{
    reqTrajRemoveLast_t req = {};
    respBool_t resp = {};

    req.h.type = WS_MSG_TRAJ_REMOVE_LAST;

    if(_rpc(req, resp))
    {
        return true;
    }

    return resp.isError != 0;
}

bool ext_setSystemParams(ext_systemParams params)
{
    reqSetSystemParams_t req = {};
    respBool_t resp = {};

    req.h.type = WS_MSG_SET_SYSTEM_PARAMS;
    req.p = params;

    if(_rpc(req, resp))
    {
        return true;
    }

    return resp.isError != 0;
}

ext_snapshotData ext_getSnapshot(void)
{
    ext_snapshotData ret = {};
    reqGetSnapshot_t req = {};
    respGetSnapshot_t resp = {};

    req.h.type = WS_MSG_GET_SNAPSHOT;

    if(_rpc(req, resp))
    {
        ret.isError = true;
        return ret;
    }

    ret.time_seconds = resp.time_seconds;
    ret.state = resp.state;
    ret.err = resp.err;
    ret.isError = resp.isError != 0;

    return ret;
}

bool ext_run(void)
{
    reqRun_t req = {};
    respBool_t resp = {};

    req.h.type = WS_MSG_RUN;

    if(_rpc(req, resp))
    {
        return true;
    }

    return resp.isError != 0;
}

bool ext_stop(void)
{
    reqStop_t req = {};
    respBool_t resp = {};

    req.h.type = WS_MSG_STOP;

    if(_rpc(req, resp))
    {
        return true;
    }

    return resp.isError != 0;
}

ext_plantSnapshotData ext_getPlantSnapshot(void)
{
    ext_plantSnapshotData ret = {};
    reqGetPlantSnapshot_t req = {};
    respGetPlantSnapshot_t resp = {};

    req.h.type = WS_MSG_GET_PLANT_SNAPSHOT;

    if(_rpc(req, resp))
    {
        ret.isAttached = true;
        ret.isReadyToStart = true;
        ret.isError = true;
        return ret;
    }

    ret.time_seconds = resp.time_seconds;
    ret.sequence = resp.sequence;
    ret.state = resp.state;
    ret.isAttached = resp.isAttached != 0;
    ret.isReadyToStart = resp.isReadyToStart != 0;
    ret.isError = resp.isError != 0;

    return ret;
}

bool ext_beginStaging(ext_coord_t safetyAltitude)
{
    reqBeginStaging_t req = {};
    respBool_t resp = {};

    req.h.type = WS_MSG_BEGIN_STAGING;
    req.safetyAltitude = safetyAltitude;

    if(_rpc(req, resp))
    {
        return true;
    }

    return resp.isError != 0;
}

bool ext_stopStaging(void)
{
    reqStopStaging_t req = {};
    respBool_t resp = {};

    req.h.type = WS_MSG_STOP_STAGING;

    if(_rpc(req, resp))
    {
        return true;
    }

    return resp.isError != 0;
}

bool ext_initQuadRotor_MPC01(ext_initQuadRotorParams params)
{
    reqInitQuadRotorMPC_t req = {};
    respBool_t resp = {};

    req.h.type = WS_MSG_INIT_QUAD_ROTOR_MPC;
    req.p = params;

    if(_rpc(req, resp))
    {
        return true;
    }

    return resp.isError != 0;
}

ext_logBatch ext_getLogBatch(void)
{
    reqGetLogBatch_t req = {};
    respGetLogBatch_t resp = {};

    req.h.type = WS_MSG_GET_LOG_BATCH;

    if(_rpc(req, resp))
    {
        // Err
        return {};
    }

    return resp.p;
}

ext_moduleList ext_getLogModules(void)
{
    reqGetLogModules_t req = {};
    respGetLogModules_t resp = {};

    req.h.type = WS_MSG_GET_LOG_MODULES;

    if(_rpc(req, resp))
    {
        // Err
        return {};
    }

    return resp.p;
}

bool ext_setLogLevel(ext_logLevelParams params)
{
    reqSetLogLevel_t req = {};
    respBool_t resp = {};

    req.h.type = WS_MSG_SET_LOG_LEVEL;
    req.p = params;

    if(_rpc(req, resp))
    {
        return true;
    }

    return resp.isError != 0;
}

ext_moduleList ext_getProfilerModules(void)
{
    reqGetProfilerModules_t req = {};
    respGetProfilerModules_t resp = {};

    req.h.type = WS_MSG_GET_PROFILER_MODULES;

    if(_rpc(req, resp))
    {
        // Err
        return {};
    }

    return resp.p;
}

bool ext_setProfilerEnabled(ext_profilerEnableParams params)
{
    reqSetProfilerEnabled_t req = {};
    respBool_t resp = {};

    req.h.type = WS_MSG_SET_PROFILER_ENABLED;
    req.module = params.module;
    req.enabled = params.enabled ? 1 : 0;

    if(_rpc(req, resp))
    {
        return true;
    }

    return resp.isError != 0;
}

ext_profilerTable ext_getProfilerTable(void)
{
    reqGetProfilerTable_t req = {};
    respGetProfilerTable_t resp = {};

    req.h.type = WS_MSG_GET_PROFILER_TABLE;

    if(_rpc(req, resp))
    {
        // Err
        return {};
    }

    return resp.p;
}

bool ext_resetProfiler(void)
{
    reqResetProfiler_t req = {};
    respBool_t resp = {};

    req.h.type = WS_MSG_RESET_PROFILER;

    if(_rpc(req, resp))
    {
        return true;
    }

    return resp.isError != 0;
}

bool ext_setDiagFiles(ext_diagFiles params)
{
    reqSetDiagFiles_t req = {};
    respBool_t resp = {};

    req.h.type = WS_MSG_SET_DIAG_FILES;
    req.logFile = params.logFile ? 1 : 0;
    req.profileRaw = params.profileRaw ? 1 : 0;

    if(_rpc(req, resp))
    {
        return true;
    }

    return resp.isError != 0;
}

ext_recordStatus ext_setRecording(ext_recordParams params)
{
    reqSetRecording_t req = {};
    respSetRecording_t resp = {};

    req.h.type = WS_MSG_SET_RECORDING;
    req.enabled = params.enabled ? 1 : 0;

    if(_rpc(req, resp))
    {
        // Err
        return {};
    }

    return resp.p;
}

ext_recordStatus ext_getRecordStatus(void)
{
    reqGetRecordStatus_t req = {};
    respGetRecordStatus_t resp = {};

    req.h.type = WS_MSG_GET_RECORD_STATUS;

    if(_rpc(req, resp))
    {
        // Err
        return {};
    }

    return resp.p;
}

bool ext_initRocket_MPC01(ext_initRocketParams params)
{
    reqInitRocketMPC_t req = {};
    respBool_t resp = {};

    req.h.type = WS_MSG_INIT_ROCKET_MPC;
    req.p = params;

    if(_rpc(req, resp))
    {
        return true;
    }

    return resp.isError != 0;
}

ext_paramManifest ext_modelGetManifest(void)
{
    reqModelGetManifest_t req = {};
    respModelGetManifest_t resp = {};

    req.h.type = WS_MSG_MODEL_GET_MANIFEST;

    if(_rpc(req, resp))
    {
        // Err
        return {};
    }

    return resp.p;
}

bool ext_modelSetParam(ext_paramSet params)
{
    reqModelSetParam_t req = {};
    respBool_t resp = {};

    req.h.type = WS_MSG_MODEL_SET_PARAM;
    req.p = params;

    if(_rpc(req, resp))
    {
        return true;
    }

    return resp.isError != 0;
}

ext_paramManifest ext_controllerGetManifest(void)
{
    reqControllerGetManifest_t req = {};
    respControllerGetManifest_t resp = {};

    req.h.type = WS_MSG_CONTROLLER_GET_MANIFEST;

    if(_rpc(req, resp))
    {
        // Err
        return {};
    }

    return resp.p;
}

bool ext_controllerSetParam(ext_paramSet params)
{
    reqControllerSetParam_t req = {};
    respBool_t resp = {};

    req.h.type = WS_MSG_CONTROLLER_SET_PARAM;
    req.p = params;

    if(_rpc(req, resp))
    {
        return true;
    }

    return resp.isError != 0;
}

ext_paramManifest ext_observerGetManifest(void)
{
    reqObserverGetManifest_t req = {};
    respObserverGetManifest_t resp = {};

    req.h.type = WS_MSG_OBSERVER_GET_MANIFEST;

    if(_rpc(req, resp))
    {
        // Err
        return {};
    }

    return resp.p;
}

bool ext_observerSetParam(ext_paramSet params)
{
    reqObserverSetParam_t req = {};
    respBool_t resp = {};

    req.h.type = WS_MSG_OBSERVER_SET_PARAM;
    req.p = params;

    if(_rpc(req, resp))
    {
        return true;
    }

    return resp.isError != 0;
}

ext_paramManifest ext_sensorGetManifest(void)
{
    reqSensorGetManifest_t req = {};
    respSensorGetManifest_t resp = {};

    req.h.type = WS_MSG_SENSOR_GET_MANIFEST;

    if(_rpc(req, resp))
    {
        // Err
        return {};
    }

    return resp.p;
}

bool ext_sensorSetParam(ext_paramSet params)
{
    reqSensorSetParam_t req = {};
    respBool_t resp = {};

    req.h.type = WS_MSG_SENSOR_SET_PARAM;
    req.p = params;

    if(_rpc(req, resp))
    {
        return true;
    }

    return resp.isError != 0;
}
