/* dynamics_rocket_mpc_01.hpp -- generated by dynamics_rocket_MPC01.ipynb.
 * Author: Diego Perazzolo. Do not edit by hand.
 * MPC prediction model: dynamics f(x,u) + Jacobians f_x, f_u. No control law.
 */
#pragma once
#include <array>
#include <cstddef>

namespace CDS { namespace Dynamics {

class ROCKET_MPC_01 {
public:
    static constexpr std::size_t STATE_DIM = 12;
    static constexpr std::size_t INPUT_DIM = 4;
    using StateVec   = std::array<double, STATE_DIM>;
    using InputVec   = std::array<double, INPUT_DIM>;
    using UserForces = std::array<double, 3>;

    enum class StateName : std::size_t {
        X = 0,
        Y = 1,
        Z = 2,
        Alpha = 3,
        Beta = 4,
        Psi = 5,
        XDot = 6,
        YDot = 7,
        ZDot = 8,
        AlphaDot = 9,
        BetaDot = 10,
        PsiDot = 11,
    };
    enum class ParamName : std::size_t {
        Mass = 0,
        Ix = 1,
        Iy = 2,
        Iz = 3,
        Gravity = 4,
        DragLateral = 5,
        DragAxial = 6,
        ThrustMax = 7,
        ThrustMin = 8,
        TorqueXMax = 9,
        TorqueXMin = 10,
        TorqueYMax = 11,
        TorqueYMin = 12,
        TorqueZMax = 13,
        TorqueZMin = 14,
    };

    ROCKET_MPC_01();

    // State derivative dx/dt = f(x, u) + world-frame external force userF.
    StateVec Dynamics(const StateVec& s, const InputVec& u, const UserForces& userF) const;
    // Jacobians of f at (x,u): fx = df/dx (STATE x STATE), fu = df/du (STATE x INPUT).
    // userF is additive, so it does not enter the Jacobians.
    void Jacobians(const StateVec& s, const InputVec& u,
                   double fx[STATE_DIM][STATE_DIM], double fu[STATE_DIM][INPUT_DIM]) const;

    static double GetState(const StateVec& s, StateName n);
    static void   SetState(StateVec& s, StateName n, double v);
    double GetParam(ParamName n) const;
    void   SetParam(ParamName n, double v);
    static constexpr std::size_t StateToIdx(StateName n) noexcept { return static_cast<std::size_t>(n); }

private:
    struct PhysicsParams {
            double m = 10.0;  // vehicle mass [kg]
            double Ix = 3.3333333333333335;  // inertia around body x [kg m^2]
            double Iy = 3.3333333333333335;  // inertia around body y [kg m^2]
            double Iz = 1.0;  // inertia around body z [kg m^2]
            double g = 9.81;  // gravity [m/s^2]
            double c = 1.0;  // lateral drag coeff (body x, y) [N s/m]
            double cz = 0.02;  // axial drag coeff (body z) [N s/m]
            double F1_max = 500.0;  // thrust upper saturation [N]
            double F1_min = 0.0;  // thrust lower saturation [N]
            double T1_max = 10;  // Torque T1, about body y axis (drives alpha), upper saturation [Nm]
            double T1_min = -10;  // Torque T1, about body y axis (drives alpha), lower saturation [Nm]
            double T2_max = 10;  // Torque T2, about body x axis (drives beta), upper saturation [Nm]
            double T2_min = -10;  // Torque T2, about body x axis (drives beta), lower saturation [Nm]
            double T3_max = 10;  // Torque T3, about body z axis (drives psi), upper saturation [Nm]
            double T3_min = -10;  // Torque T3, about body z axis (drives psi), lower saturation [Nm]
    };
    PhysicsParams m_p;
};

} }  // namespace CDS::Dynamics
