# =============================================================================
# Controlled Descent Simulator
# =============================================================================
# File        : gen_ext.py
# Description : Generator for the ext API boundary. Reads the declarative
#               description in ext_api.py and (re)generates, under the
#               exported_cpp/ folders:
#                 apps/common/exported_cpp/ext_defs.hpp      struct definitions
#                 apps/common/exported_cpp/ext_comm.hpp      API contract
#                 apps/common/exported_cpp/bindings.cpp      embind bindings
#                 apps/ws-served/exported_cpp/ws_protocol.hpp    wire protocol
#                 apps/ws-served/exported_cpp/ext_comm_ws.cpp    client marshalling
#                 apps/ws-served/exported_cpp/dispatch.cpp       server dispatch
#               The direct adapter (apps/common/ext_comm.cpp) stays
#               hand-written: it contains semantics, not mechanics.
#               The app CMakeLists re-run this automatically when
#               ext_api.py / gen_ext.py change (see gen_ext.cmake).
# Usage       : python3 apps/common/gen_ext.py           regenerate all files
#               python3 apps/common/gen_ext.py --check   verify files in sync
# =============================================================================
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ext_api import DEFS, COMM, COMMANDS, Struct, Raw  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

STRUCTS = {s.name: s for s in DEFS + COMM if isinstance(s, Struct)}

# --------------------------------------------------------------------------- #
# common text                                                                  #
# --------------------------------------------------------------------------- #

LICENSE = """\
// =============================================================================
// Controlled Descent Simulator
// =============================================================================
//
// Copyright (c) 2026 Diego Perazzolo
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//
// =============================================================================
"""


def header(filename, description_lines):
    out = LICENSE
    out += f"// File        : {filename}\n"
    first = True
    for line in description_lines:
        tag = "// Description :" if first else "//              "
        out += f"{tag} {line}\n" if line else "//\n"
        first = False
    out += "// Author      : Diego Perazzolo\n"
    out += "// Created     : 2026\n"
    out += ("// GENERATED by apps/common/gen_ext.py from apps/common/ext_api.py"
            " — DO NOT EDIT BY HAND\n")
    out += "// =============================================================================\n"
    return out


# --------------------------------------------------------------------------- #
# helpers                                                                      #
# --------------------------------------------------------------------------- #

BASE_SIZES = {"ext_coord_t": 4, "bool": 1, "uint8_t": 1}


def size_of(type_name):
    if type_name in BASE_SIZES:
        return BASE_SIZES[type_name]
    return sum(size_of(f.type) for f in STRUCTS[type_name].fields)


def has_bool(type_name):
    if type_name == "bool":
        return True
    if type_name in BASE_SIZES:
        return False
    return any(has_bool(f.type) for f in STRUCTS[type_name].fields)


def enum_name(cmd):
    """InitRocket -> WS_MSG_INIT_ROCKET"""
    out = ""
    for i, ch in enumerate(cmd.wire):
        if ch.isupper() and i > 0 and not cmd.wire[i - 1].isupper():
            out += "_"
        out += ch.upper()
    return "WS_MSG_" + out


def req_size(cmd):
    n = 1  # header_t
    if cmd.req is None:
        return n
    if isinstance(cmd.req, tuple):
        return n + size_of(cmd.req[1])
    return n + size_of(cmd.req)


def resp_size(cmd):
    if cmd.resp == "bool":
        return 2  # header_t + uint8_t
    n = 1
    for f in STRUCTS[cmd.resp].fields:
        n += 1 if f.type == "bool" else size_of(f.type)
    return n


def req_breakdown(cmd):
    if cmd.req is None:
        return ""
    if isinstance(cmd.req, tuple):
        return f" // 1 + {size_of(cmd.req[1]) // 4}f"
    if has_bool(cmd.req):
        return _field_breakdown(cmd.req)
    return f" // 1 + {size_of(cmd.req) // 4}f"


def resp_breakdown(cmd):
    if cmd.resp == "bool":
        return " // 1 + u8"
    return _field_breakdown(cmd.resp)


def _field_breakdown(struct_name):
    parts = []
    for f in STRUCTS[struct_name].fields:
        parts.append("u8" if f.type == "bool" else f"{size_of(f.type) // 4}f")
    return " // 1 + " + " + ".join(parts)


def _check_no_nested_bool(struct_name):
    """bool is converted to uint8_t on the wire, but only at the top level of
    request/response structs: a bool buried in a nested struct would cross
    the wire raw. Fail generation loudly instead."""
    for f in STRUCTS[struct_name].fields:
        if f.type not in BASE_SIZES and has_bool(f.type):
            raise SystemExit(
                f"ext_api.py: {struct_name}.{f.name} nests a bool inside "
                f"{f.type} — not supported on the wire, move the bool to the "
                f"top level of {struct_name}")


def struct_block(s):
    """Emit one typedef struct with its comments."""
    out = ""
    if s.doc is not None:
        if s.doc_style == "//":
            out += f"// {s.doc}\n"
        else:
            lines = s.doc.split("\n")
            if len(lines) == 1:
                out += f"/* {lines[0]} */\n"
            else:
                out += f"/* {lines[0]}\n"
                out += "\n".join(lines[1:]) + " */\n"
    out += "typedef struct\n{\n"
    for f in s.fields:
        if f.blank_before:
            out += "\n"
        if f.pre is not None:
            lines = f.pre.split("\n")
            if len(lines) == 1:
                out += f"    /* {lines[0]} */\n"
            else:
                out += f"    /* {lines[0]}\n"
                for line in lines[1:-1]:
                    out += f"    {line}\n"
                out += f"    {lines[-1]} */\n"
        out += f"    {f.type} {f.name};"
        if f.doc:
            out += f" // {f.doc}"
        out += "\n"
        if f.post is not None:
            out += f"    {f.post}\n"
    out += f"}} {s.name};\n"
    return out


def cfn_signature(cmd):
    if cmd.req is None:
        return f"{cfn_ret(cmd)} {cmd.cfn}(void)"
    if isinstance(cmd.req, tuple):
        _, t, n = cmd.req
        return f"{cfn_ret(cmd)} {cmd.cfn}({t} {n})"
    return f"{cfn_ret(cmd)} {cmd.cfn}({cmd.req} params)"


def cfn_ret(cmd):
    return cmd.resp


# --------------------------------------------------------------------------- #
# apps/common/ext_defs.hpp                                                     #
# --------------------------------------------------------------------------- #

def gen_ext_defs():
    out = header("ext_defs.hpp", [
        "Struct definitions of the external communication API (the",
        "boundary shared by all apps and the embind bindings)",
    ])
    out += "\n#pragma once\n"
    blocks = []
    for item in DEFS:
        if isinstance(item, Raw):
            blocks.append(item.text)
        else:
            blocks.append(struct_block(item).rstrip("\n"))
    out += "\n\n".join(blocks) + "\n"
    return out


# --------------------------------------------------------------------------- #
# apps/common/ext_comm.hpp                                                     #
# --------------------------------------------------------------------------- #

def gen_ext_comm_hpp():
    out = header("ext_comm.hpp", [
        "External communication API (ext ↔ core adapter layer).",
        "Contract implemented by every adapter: ext_comm.cpp calls the",
        "core directly (wasm-only, ws-served server), ext_comm_ws.cpp",
        "forwards over WebSocket (ws-served client).",
    ])
    out += "#pragma once\n#include \"ext_defs.hpp\"\n\n/* structs */\n"
    for s in COMM:
        out += "\n" + struct_block(s)
    out += "\n"
    decls = []
    for cmd in COMMANDS:
        decls.append(f"/* {cmd.doc} */\n{cfn_signature(cmd)};\n")
    out += "\n".join(decls)
    return out


# --------------------------------------------------------------------------- #
# apps/common/bindings.cpp                                                     #
# --------------------------------------------------------------------------- #

def gen_bindings():
    out = header("bindings.cpp", [
        "Emscripten embind bindings: exposes the ext structs and the",
        "API functions to JavaScript. Identical for every browser app.",
    ])
    out += "\n#include <emscripten/bind.h>\n#include \"ext_comm.hpp\"\n\n"
    out += "using namespace emscripten;\n\n"
    out += "EMSCRIPTEN_BINDINGS(simulator) {\n\n"
    out += "    // --- Value types (struct) ---\n"

    structs = [s for s in DEFS + COMM if isinstance(s, Struct) and s.bind]
    blocks = []
    for s in structs:
        width = max(len(f.js) for f in s.fields) + 3  # name + quotes + comma
        b = f"    value_object<{s.name}>(\"{s.name}\")\n"
        rows = []
        for f in s.fields:
            js = f'"{f.js}",'
            rows.append(f"        .field({js:<{width}} &{s.name}::{f.name})")
        b += "\n".join(rows) + ";\n"
        blocks.append(b)
    out += "\n".join(blocks)

    out += "\n    // --- Functions exposed to JS ---\n"
    for cmd in COMMANDS:
        out += f"    function(\"{cmd.js}\", &{cmd.cfn});\n"
    out += "}\n"
    return out


# --------------------------------------------------------------------------- #
# apps/ws-served/ws_protocol.hpp                                               #
# --------------------------------------------------------------------------- #

def wire_req_name(cmd):
    return f"req{cmd.wire}_t"


def wire_resp_name(cmd):
    if cmd.resp == "bool":
        return "respBool_t"
    return f"resp{cmd.wire}_t"


def gen_ws_protocol():
    out = header("ws_protocol.hpp", [
        "Binary wire protocol shared between the WASM WebSocket proxy",
        "(client/ext_comm_ws.cpp) and the native core server",
        "(server/main.cpp + dispatch.cpp).",
        "One request -> one response. Packed little-endian structs;",
        "both peers are little-endian (WASM and x86/ARM).",
        "Request/response correlation is NOT part of this protocol:",
        "it is owned by the libs/ws transport, which frames every",
        "message with its own id before it reaches the wire.",
    ])
    out += "#pragma once\n#include <cstdint>\n#include \"ext_comm.hpp\"\n\n"
    out += "namespace ws_proto {\n\n"
    out += "constexpr uint16_t WS_DEFAULT_PORT = 9002;\n\n"

    # enum
    out += "/* Message types: request and matching response carry the same type id */\n"
    out += "enum MsgType : uint8_t\n{\n"
    ew = max(len(enum_name(c)) for c in COMMANDS)
    for cmd in COMMANDS:
        out += f"    {enum_name(cmd):<{ew}} = {cmd.id}, // -> {wire_resp_name(cmd)}\n"
    out += "};\n\n"

    out += "#pragma pack(push, 1)\n\n"
    out += "/* Common message header: every request/response starts with this */\n"
    out += "typedef struct\n{\n    uint8_t type; // MsgType, echoed in the response\n} header_t;\n\n"

    # validate wire-crossing structs before emitting anything
    for cmd in COMMANDS:
        if cmd.req is not None and not isinstance(cmd.req, tuple):
            _check_no_nested_bool(cmd.req)
        if cmd.resp != "bool":
            _check_no_nested_bool(cmd.resp)

    # requests: structs containing bool are expanded field by field with
    # bool -> uint8_t, exactly like the responses (symmetric conversion)
    out += "/* ------------------------------- requests ------------------------------- */\n"
    for cmd in COMMANDS:
        out += "\ntypedef struct\n{\n    header_t h;\n"
        if isinstance(cmd.req, tuple):
            _, t, n = cmd.req
            out += f"    {t} {n};\n"
        elif cmd.req is not None:
            if has_bool(cmd.req):
                for f in STRUCTS[cmd.req].fields:
                    t = "uint8_t" if f.type == "bool" else f.type
                    out += f"    {t} {f.name};\n"
            else:
                out += f"    {cmd.req} p;\n"
        out += f"}} {wire_req_name(cmd)};\n"

    # responses
    out += "\n/* ------------------------------ responses ------------------------------- */\n"
    out += "\n/* generic boolean response: isError follows the core convention (1 = error) */\n"
    out += "typedef struct\n{\n    header_t h;\n    uint8_t isError;\n} respBool_t;\n"
    for cmd in COMMANDS:
        if cmd.resp == "bool":
            continue
        out += "\ntypedef struct\n{\n    header_t h;\n"
        s = STRUCTS[cmd.resp]
        if has_bool(cmd.resp):
            for f in s.fields:
                t = "uint8_t" if f.type == "bool" else f.type
                out += f"    {t} {f.name};\n"
        else:
            out += f"    {cmd.resp} p;\n"
        out += f"}} {wire_resp_name(cmd)};\n"

    out += "\n#pragma pack(pop)\n\n"

    out += "/* Largest message either peer can send: used to size the shared RPC buffer */\n"
    out += "constexpr uint32_t WS_MAX_MSG_SIZE = 256;\n\n"

    # size asserts
    out += """\
/* Exact wire sizes, computed by the generator (f = sizeof(ext_coord_t) = 4):
   each peer checks them against its own ABI at compile time, so any layout
   drift (padding from mixed-size fields, architecture-dependent type widths)
   breaks the build instead of silently corrupting the parsing. */
"""
    rows = []
    for cmd in COMMANDS:
        rows.append((wire_req_name(cmd), req_size(cmd), req_breakdown(cmd)))
    seen_resp = set()
    for cmd in COMMANDS:
        name = wire_resp_name(cmd)
        if name in seen_resp:
            continue
        seen_resp.add(name)
        rows.append((name, resp_size(cmd), resp_breakdown(cmd)))
    nw = max(len(r[0]) for r in rows)
    out += f"static_assert(sizeof(header_t){' ' * (nw - len('header_t'))} ==  1, \"wire layout drift\");\n"
    for name, size, note in rows:
        out += (f"static_assert(sizeof({name}){' ' * (nw - len(name))} == "
                f"{size:>2}, \"wire layout drift\");{note}\n")
    for cmd in COMMANDS:
        assert req_size(cmd) < 256 and resp_size(cmd) < 256, "grow WS_MAX_MSG_SIZE"
    out += "\nstatic_assert(sizeof(reqTrajAppendPoly4_t) < WS_MAX_MSG_SIZE, \"wire msg too big\");\n"
    out += "static_assert(sizeof(respStep_t) < WS_MAX_MSG_SIZE, \"wire msg too big\");\n"
    out += "\n} // namespace ws_proto\n"
    return out


# --------------------------------------------------------------------------- #
# apps/ws-served/client/ext_comm_ws.cpp                                        #
# --------------------------------------------------------------------------- #

CLIENT_PRELUDE = """\
#include <cstdint>
#include "ext_comm.hpp"
#include "ws_protocol.hpp"
#include "ws_rpc_client.hpp"

using namespace ws_proto;

/* Static functions */

/* Round-trips one request/response pair, returns true on error */
template <typename Req, typename Resp>
static bool _rpc(Req& req, Resp& resp)
{
    int n = ws_rpc(reinterpret_cast<const uint8_t*>(&req), sizeof(Req),
                   reinterpret_cast<uint8_t*>(&resp), sizeof(Resp));

    if(n != (int)sizeof(Resp))
    {
        // Err: transport failure or unexpected response size
        return true;
    }

    if(resp.h.type != req.h.type)
    {
        // Err: response does not match the request
        return true;
    }

    return false;
}

/* ext functions */
"""


def gen_client():
    out = header("ext_comm_ws.cpp", [
        "WebSocket adapter of the external communication API.",
        "Drop-in replacement for ext_comm.cpp: instead of calling the",
        "core directly, every ext_* call is marshalled into a",
        "ws_protocol message and round-tripped through the libs/ws",
        "synchronous RPC transport (ws_rpc_client) to a native server",
        "running the core. See ws_rpc_client.hpp for the transport",
        "requirements (COOP/COEP, bridge worker) and URL selection.",
    ])
    out += "\n" + CLIENT_PRELUDE

    for cmd in COMMANDS:
        rq, rs = wire_req_name(cmd), wire_resp_name(cmd)
        out += f"\n{cfn_signature(cmd)}\n{{\n"

        if cmd.resp == "bool":
            out += f"    {rq} req = {{}};\n    {rs} resp = {{}};\n\n"
            out += f"    req.h.type = {enum_name(cmd)};\n"
            out += _fill_req(cmd)
            out += "\n    if(_rpc(req, resp))\n    {\n        return true;\n    }\n\n"
            out += "    return resp.isError != 0;\n"
        elif has_bool(cmd.resp):
            s = STRUCTS[cmd.resp]
            out += f"    {cmd.resp} ret = {{}};\n"
            out += f"    {rq} req = {{}};\n    {rs} resp = {{}};\n\n"
            out += f"    req.h.type = {enum_name(cmd)};\n"
            out += _fill_req(cmd)
            bools = [f.name for f in s.fields if f.type == "bool"]
            out += "\n    if(_rpc(req, resp))\n    {\n"
            for b in bools:
                out += f"        ret.{b} = true;\n"
            out += "        return ret;\n    }\n\n"
            for f in s.fields:
                if f.type == "bool":
                    out += f"    ret.{f.name} = resp.{f.name} != 0;\n"
                else:
                    out += f"    ret.{f.name} = resp.{f.name};\n"
            out += "\n    return ret;\n"
        else:
            out += f"    {rq} req = {{}};\n    {rs} resp = {{}};\n\n"
            out += f"    req.h.type = {enum_name(cmd)};\n"
            out += _fill_req(cmd)
            out += "\n    if(_rpc(req, resp))\n    {\n        // Err\n        return {};\n    }\n\n"
            out += "    return resp.p;\n"
        out += "}\n"
    return out


def _fill_req(cmd):
    if cmd.req is None:
        return ""
    if isinstance(cmd.req, tuple):
        _, _, n = cmd.req
        return f"    req.{n} = {n};\n"
    if has_bool(cmd.req):
        out = ""
        for f in STRUCTS[cmd.req].fields:
            if f.type == "bool":
                out += f"    req.{f.name} = params.{f.name} ? 1 : 0;\n"
            else:
                out += f"    req.{f.name} = params.{f.name};\n"
        return out
    return "    req.p = params;\n"


# --------------------------------------------------------------------------- #
# apps/ws-served/server/dispatch.cpp                                           #
# --------------------------------------------------------------------------- #

DISPATCH_PRELUDE = """\
#include "dispatch.hpp"

#include <cstdio>
#include <cstring>

#include "ext_comm.hpp"
#include "ws_protocol.hpp"

using namespace ws_proto;

/* Static functions */

/* Copy a wire request into its typed struct, returns true on size mismatch */
template <typename Req>
static bool _parse(const std::vector<uint8_t>& msg, Req& req)
{
    if(msg.size() != sizeof(Req))
    {
        // Err: malformed request
        return true;
    }
    memcpy(&req, msg.data(), sizeof(Req));
    return false;
}

template <typename Resp>
static std::vector<uint8_t> _serialize(const Resp& resp)
{
    std::vector<uint8_t> out(sizeof(Resp));
    memcpy(out.data(), &resp, sizeof(Resp));
    return out;
}

static std::vector<uint8_t> _respBool(const header_t& h, bool isError)
{
    respBool_t resp = {};
    resp.h = h;
    resp.isError = isError ? 1 : 0;
    return _serialize(resp);
}

/* Dispatch one request to the ext communication layer */
std::vector<uint8_t> server_dispatch(const std::vector<uint8_t>& msg)
{
    if(msg.size() < sizeof(header_t))
    {
        // Err: too short to carry a header, no way to answer meaningfully
        return {};
    }

    header_t h = {};
    memcpy(&h, msg.data(), sizeof(header_t));

    switch(h.type)
    {
"""


def gen_dispatch():
    out = header("dispatch.cpp", [
        "ws_protocol request dispatcher — see dispatch.hpp.",
    ])
    out += "\n" + DISPATCH_PRELUDE

    cases = []
    for cmd in COMMANDS:
        rq = wire_req_name(cmd)
        b = f"        case {enum_name(cmd)}:\n        {{\n"
        b += f"            {rq} req = {{}};\n"
        b += "            if(_parse(msg, req)) return _respBool(h, true);\n\n"
        if cmd.log:
            b += f"            printf(\"[cds-server] {cmd.log}\\n\");\n"
        setup, call = _dispatch_call(cmd)
        b += setup
        if cmd.resp == "bool":
            b += f"            return _respBool(h, {call});\n"
        elif has_bool(cmd.resp):
            s = STRUCTS[cmd.resp]
            b += f"            {cmd.resp} ret = {call};\n\n"
            b += f"            {wire_resp_name(cmd)} resp = {{}};\n"
            b += "            resp.h = h;\n"
            for f in s.fields:
                if f.type == "bool":
                    b += f"            resp.{f.name} = ret.{f.name} ? 1 : 0;\n"
                else:
                    b += f"            resp.{f.name} = ret.{f.name};\n"
            b += "            return _serialize(resp);\n"
        else:
            b += f"            {wire_resp_name(cmd)} resp = {{}};\n"
            b += "            resp.h = h;\n"
            b += f"            resp.p = {call};\n"
            b += "            return _serialize(resp);\n"
        b += "        }\n"
        cases.append(b)
    out += "\n".join(cases)

    out += """
        default:
            // Err: unknown message type
            return _respBool(h, true);
    }
}
"""
    return out


def _dispatch_call(cmd):
    """Returns (setup lines, call expression) to invoke the ext function."""
    if cmd.req is None:
        return "", f"{cmd.cfn}()"
    if isinstance(cmd.req, tuple):
        _, _, n = cmd.req
        return "", f"{cmd.cfn}(req.{n})"
    if has_bool(cmd.req):
        setup = f"            {cmd.req} par = {{}};\n"
        for f in STRUCTS[cmd.req].fields:
            if f.type == "bool":
                setup += f"            par.{f.name} = req.{f.name} != 0;\n"
            else:
                setup += f"            par.{f.name} = req.{f.name};\n"
        setup += "\n"
        return setup, f"{cmd.cfn}(par)"
    return "", f"{cmd.cfn}(req.p)"


# --------------------------------------------------------------------------- #
# main                                                                         #
# --------------------------------------------------------------------------- #

TARGETS = {
    "apps/common/exported_cpp/ext_defs.hpp": gen_ext_defs,
    "apps/common/exported_cpp/ext_comm.hpp": gen_ext_comm_hpp,
    "apps/common/exported_cpp/bindings.cpp": gen_bindings,
    "apps/ws-served/exported_cpp/ws_protocol.hpp": gen_ws_protocol,
    "apps/ws-served/exported_cpp/ext_comm_ws.cpp": gen_client,
    "apps/ws-served/exported_cpp/dispatch.cpp": gen_dispatch,
}


def main():
    check = "--check" in sys.argv
    stale = []
    for rel, gen in TARGETS.items():
        path = os.path.join(ROOT, rel)
        content = gen()
        current = None
        if os.path.exists(path):
            with open(path) as fh:
                current = fh.read()
        if check:
            if current != content:
                stale.append(rel)
        elif current != content:
            # write only when the content changed, so untouched files keep
            # their mtime and the build trees do not recompile needlessly
            with open(path, "w") as fh:
                fh.write(content)
            print(f"generated {rel}")
        else:
            print(f"unchanged {rel}")
    if check:
        if stale:
            print("OUT OF SYNC with apps/common/ext_api.py:")
            for rel in stale:
                print(f"  {rel}")
            print("run: python3 apps/common/gen_ext.py")
            sys.exit(1)
        print("all generated files are in sync")


if __name__ == "__main__":
    main()
