/* dynamics_rocket_ff_lqr_01.cpp -- generated by dynamics_rocket_FFLQR01.ipynb.
 * Author: Diego Perazzolo. Do not edit by hand.
 */
#include "dynamics_rocket_ff_lqr_01.hpp"
#include <cmath>
#include <algorithm>

namespace CDS { namespace Dynamics {

const double ROCKET_FF_LQR_01::A_e[16][16] = {
    {0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0},
    {0, 0, 0, 9.8100000000000005, 0, 0, -0.10000000000000001, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, -9.8100000000000005, 0, 0, -0.10000000000000001, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, -0.002, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {-1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, -1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, -1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, -1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
};

const double ROCKET_FF_LQR_01::B_e[16][4] = {
    {0, 0, 0, 0},
    {0, 0, 0, 0},
    {0, 0, 0, 0},
    {0, 0, 0, 0},
    {0, 0, 0, 0},
    {0, 0, 0, 0},
    {0, 0, 0, 0},
    {0, 0, 0, 0},
    {0.10000000000000001, 0, 0, 0},
    {0, 0.29999999999999999, 0, 0},
    {0, 0, 0.29999999999999999, 0},
    {0, 0, 0, 1.0},
    {0, 0, 0, 0},
    {0, 0, 0, 0},
    {0, 0, 0, 0},
    {0, 0, 0, 0}
};

const double ROCKET_FF_LQR_01::Q_default[16][16] = {
    {1000.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 1000.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 1000.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 100.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 100.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 1000.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 1000.0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1000.0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1000.0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 100.0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 100.0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 100.0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 100.0}
};

const double ROCKET_FF_LQR_01::R_default[4][4] = {
    {1.0, 0, 0, 0},
    {0, 1.0, 0, 0},
    {0, 0, 1.0, 0},
    {0, 0, 0, 1.0}
};

const double ROCKET_FF_LQR_01::K_default[4][16] = {
    {1.5742574897078083e-14, 5.9299138503565188e-15, 39.53120887042828, 3.4185730248640535e-14, -7.4840339612533764e-14, -2.5923707624997348e-15, 1.1083692036531836e-14, 1.7645768311226441e-14, 28.115823737871359, 2.3931610068223644e-15, -7.4752404626961344e-15, -1.538586914268856e-16, -1.850851088263183e-15, -2.6493095039490126e-15, -9.9999999999999982, 3.0406425662918966e-15},
    {41.947826179826997, -5.1159076974727208e-14, 3.8985535331018357e-14, 175.0834812839654, -1.1110564279071066e-13, 7.5730985082604878e-15, 36.196261093431033, -1.2680058311107758e-14, 7.1794830204670916e-15, 46.553444647628034, -2.4141902750036999e-14, 2.2642730743052339e-15, -10.000000000000092, 9.7647873011593166e-15, -4.8897717613874313e-16, -7.6915747130231935e-16},
    {-1.3370269891453819e-13, -41.947826179826869, -3.433602266111617e-14, -3.2766679297053068e-13, 175.08348128396491, -3.6470826358936407e-13, -9.6548660003843461e-14, -36.196261093430948, -2.2425721388088405e-14, -2.4141902750036999e-14, 46.553444647628055, 3.0786766359717429e-15, 2.0931208917870245e-14, 10.00000000000013, 1.8331366162270133e-14, -3.5159236420316397e-14},
    {3.1954706405099049e-14, 5.785107773984502e-16, -4.5520537113278868e-15, 9.5101304669572576e-14, -5.2958689546598198e-14, 40.714886604804761, 2.3277688940026694e-14, 2.4380046815160919e-14, -1.5385869142688559e-15, 7.5475769143507801e-15, 1.0262255453239143e-14, 32.885099562105779, -7.8155857127703119e-15, -3.2612269336710183e-14, 2.9682884789154738e-14, -10.000000000000004}
};

ROCKET_FF_LQR_01::ROCKET_FF_LQR_01()
{
    for (std::size_t i = 0; i < 4; ++i)
        for (std::size_t j = 0; j < 16; ++j) m_K_e[i][j] = K_default[i][j];
}

void ROCKET_FF_LQR_01::SetGain(const double (&K)[4][16])
{
    for (std::size_t i = 0; i < 4; ++i)
        for (std::size_t j = 0; j < 16; ++j) m_K_e[i][j] = K[i][j];
}

double ROCKET_FF_LQR_01::GetState(const StateVec& s, StateName n) {
    switch (n) {
        case StateName::X: return s[0];
        case StateName::Y: return s[1];
        case StateName::Z: return s[2];
        case StateName::Alpha: return s[3];
        case StateName::Beta: return s[4];
        case StateName::Psi: return s[5];
        case StateName::XDot: return s[6];
        case StateName::YDot: return s[7];
        case StateName::ZDot: return s[8];
        case StateName::AlphaDot: return s[9];
        case StateName::BetaDot: return s[10];
        case StateName::PsiDot: return s[11];
        case StateName::IntX: return s[12];
        case StateName::IntY: return s[13];
        case StateName::IntZ: return s[14];
        case StateName::IntPsi: return s[15];
    }
    return 0.0;
}
void ROCKET_FF_LQR_01::SetState(StateVec& s, StateName n, double v) {
    switch (n) {
        case StateName::X: s[0] = v; return;
        case StateName::Y: s[1] = v; return;
        case StateName::Z: s[2] = v; return;
        case StateName::Alpha: s[3] = v; return;
        case StateName::Beta: s[4] = v; return;
        case StateName::Psi: s[5] = v; return;
        case StateName::XDot: s[6] = v; return;
        case StateName::YDot: s[7] = v; return;
        case StateName::ZDot: s[8] = v; return;
        case StateName::AlphaDot: s[9] = v; return;
        case StateName::BetaDot: s[10] = v; return;
        case StateName::PsiDot: s[11] = v; return;
        case StateName::IntX: s[12] = v; return;
        case StateName::IntY: s[13] = v; return;
        case StateName::IntZ: s[14] = v; return;
        case StateName::IntPsi: s[15] = v; return;
    }
}
double ROCKET_FF_LQR_01::GetParam(ParamName n) const {
    switch (n) {
        case ParamName::Mass: return m_p.m;
        case ParamName::Ix: return m_p.Ix;
        case ParamName::Iy: return m_p.Iy;
        case ParamName::Iz: return m_p.Iz;
        case ParamName::Gravity: return m_p.g;
        case ParamName::DragLateral: return m_p.c;
        case ParamName::DragAxial: return m_p.cz;
        case ParamName::ThrustMax: return m_p.F1_max;
        case ParamName::ThrustMin: return m_p.F1_min;
        case ParamName::TorqueXMax: return m_p.T1_max;
        case ParamName::TorqueXMin: return m_p.T1_min;
        case ParamName::TorqueYMax: return m_p.T2_max;
        case ParamName::TorqueYMin: return m_p.T2_min;
        case ParamName::TorqueZMax: return m_p.T3_max;
        case ParamName::TorqueZMin: return m_p.T3_min;
    }
    return 0.0;
}
void ROCKET_FF_LQR_01::SetParam(ParamName n, double v) {
    switch (n) {
        case ParamName::Mass: m_p.m = v; return;
        case ParamName::Ix: m_p.Ix = v; return;
        case ParamName::Iy: m_p.Iy = v; return;
        case ParamName::Iz: m_p.Iz = v; return;
        case ParamName::Gravity: m_p.g = v; return;
        case ParamName::DragLateral: m_p.c = v; return;
        case ParamName::DragAxial: m_p.cz = v; return;
        case ParamName::ThrustMax: m_p.F1_max = v; return;
        case ParamName::ThrustMin: m_p.F1_min = v; return;
        case ParamName::TorqueXMax: m_p.T1_max = v; return;
        case ParamName::TorqueXMin: m_p.T1_min = v; return;
        case ParamName::TorqueYMax: m_p.T2_max = v; return;
        case ParamName::TorqueYMin: m_p.T2_min = v; return;
        case ParamName::TorqueZMax: m_p.T3_max = v; return;
        case ParamName::TorqueZMin: m_p.T3_min = v; return;
    }
}

ROCKET_FF_LQR_01::StateVec ROCKET_FF_LQR_01::Dynamics(const StateVec& s, const InputVec& u,
                                    const Reference_t& ref, const Vec3& userF) const
{
    using SN = StateName;
    StateVec dxdt{};
    // Local alias: only ref.pos is used by the dynamics (integrators).
    const Vec3& ref_pos = ref.pos;

    // Precompute attitude trig (used multiple times below).
    const double sa  = std::sin(s[StateToIdx(SN::Alpha)]);
    const double ca  = std::cos(s[StateToIdx(SN::Alpha)]);
    const double sb  = std::sin(s[StateToIdx(SN::Beta)]);
    const double cb  = std::cos(s[StateToIdx(SN::Beta)]);

    // State and input aliases.
    const double xd = s[StateToIdx(SN::XDot)];
    const double yd = s[StateToIdx(SN::YDot)];
    const double zd = s[StateToIdx(SN::ZDot)];
    const double F1 = u[0];
    const double T1 = u[1];
    const double T2 = u[2];
    const double T3 = u[3];

    // Kinematics: dp/dt = v, dangles/dt = omega.
    dxdt[StateToIdx(SN::X)] = s[StateToIdx(SN::XDot)];
    dxdt[StateToIdx(SN::Y)] = s[StateToIdx(SN::YDot)];
    dxdt[StateToIdx(SN::Z)] = s[StateToIdx(SN::ZDot)];
    dxdt[StateToIdx(SN::Alpha)] = s[StateToIdx(SN::AlphaDot)];
    dxdt[StateToIdx(SN::Beta)] = s[StateToIdx(SN::BetaDot)];
    dxdt[StateToIdx(SN::Psi)] = s[StateToIdx(SN::PsiDot)];

    // Translational dynamics: dv/dt = (F_thrust + F_gravity + F_drag) / m.
    dxdt[StateToIdx(SN::XDot)] = F1*cb*sa/m_p.m + xd*(-m_p.c*ca*ca*cb*cb/m_p.m + m_p.c*cb*cb/m_p.m - m_p.c/m_p.m + m_p.cz*ca*ca*cb*cb/m_p.m - m_p.cz*cb*cb/m_p.m) + yd*(-m_p.c*cb*sa*sb/m_p.m + m_p.cz*cb*sa*sb/m_p.m) + zd*(m_p.c*ca*cb*cb*sa/m_p.m - m_p.cz*ca*cb*cb*sa/m_p.m);
    dxdt[StateToIdx(SN::YDot)] = -F1*sb/m_p.m + xd*(-m_p.c*cb*sa*sb/m_p.m + m_p.cz*cb*sa*sb/m_p.m) + yd*(-m_p.c*cb*cb/m_p.m + m_p.cz*cb*cb/m_p.m - m_p.cz/m_p.m) + zd*(-m_p.c*ca*cb*sb/m_p.m + m_p.cz*ca*cb*sb/m_p.m);
    dxdt[StateToIdx(SN::ZDot)] = F1*ca*cb/m_p.m - m_p.g + xd*(m_p.c*ca*cb*cb*sa/m_p.m - m_p.cz*ca*cb*cb*sa/m_p.m) + yd*(-m_p.c*ca*cb*sb/m_p.m + m_p.cz*ca*cb*sb/m_p.m) + zd*(m_p.c*ca*ca*cb*cb/m_p.m - m_p.c/m_p.m - m_p.cz*ca*ca*cb*cb/m_p.m);

    // User-input forces in inertial frame, divided by mass.
    dxdt[StateToIdx(SN::XDot)] += userF[0] / m_p.m;
    dxdt[StateToIdx(SN::YDot)] += userF[1] / m_p.m;
    dxdt[StateToIdx(SN::ZDot)] += userF[2] / m_p.m;

    // Rotational dynamics: I diagonal, torques are direct inputs.
    dxdt[StateToIdx(SN::AlphaDot)] = T1 / m_p.Ix;
    dxdt[StateToIdx(SN::BetaDot)]  = T2 / m_p.Iy;
    dxdt[StateToIdx(SN::PsiDot)]   = T3 / m_p.Iz;

    // Augmented states: integral of position + heading tracking error.
    dxdt[StateToIdx(SN::IntX)] = ref_pos[0] - s[StateToIdx(SN::X)];
    dxdt[StateToIdx(SN::IntY)] = ref_pos[1] - s[StateToIdx(SN::Y)];
    dxdt[StateToIdx(SN::IntZ)] = ref_pos[2] - s[StateToIdx(SN::Z)];
    // Yaw integrator error wrapped to [-pi, pi] (ref.yaw is unbounded).
    { const double dpsi = ref.yaw - s[StateToIdx(SN::Psi)];
      dxdt[StateToIdx(SN::IntPsi)] = std::atan2(std::sin(dpsi), std::cos(dpsi)); }

    return dxdt;
}

ROCKET_FF_LQR_01::InputVec ROCKET_FF_LQR_01::ExecuteControl(const StateVec& s, const Reference_t& r) const
{
    // Pull reference derivatives into named locals for clarity.
    // The tilt-angle FF is only defined for thrust-positive references
    // (az + g > 0): at az <= -g the FF angles flip / their rate expressions
    // divide by zero (free-fall singularity). Clamp az to keep the FF
    // well-posed; trajectories demanding > 1 g downward are out of envelope.
    const double ax = r.acc[0], ay = r.acc[1];
    const double az = std::max(r.acc[2], -m_p.g + 1e-6);
    const double jx = r.jerk[0], jy = r.jerk[1], jz = r.jerk[2];
    const double sx = r.snap[0], sy = r.snap[1], sz = r.snap[2];

    // Feedforward thrust magnitude and tilt angles from desired acceleration.
    const double F1_ff        = m_p.m*std::sqrt(ax*ax + ay*ay + std::pow(az + m_p.g, 2));
    const double alpha_ff     = std::atan2(ax, az + m_p.g);
    const double beta_ff      = std::atan2(-ay, std::sqrt(ax*ax + std::pow(az + m_p.g, 2)));
    const double alpha_ff_dot = (-ax*jz + jx*(az + m_p.g))/(ax*ax + std::pow(az + m_p.g, 2));
    const double beta_ff_dot  = std::pow(ax*ax + std::pow(az + m_p.g, 2), -0.5)*(ay*(ax*jx + jz*(az + m_p.g)) - jy*(ax*ax + std::pow(az + m_p.g, 2)))/(ax*ax + ay*ay + std::pow(az + m_p.g, 2));
    const double T1_ff        = m_p.Ix*(2.0*ax*jz*(ax*jx + jz*(az + m_p.g)) - 2.0*jx*(az + m_p.g)*(ax*jx + jz*(az + m_p.g)) + (ax*ax + std::pow(az + m_p.g, 2))*(-ax*sz + sx*(az + m_p.g)))/std::pow(ax*ax + std::pow(az + m_p.g, 2), 2);
    const double T2_ff        = -m_p.Iy*std::pow(ax*ax + std::pow(az + m_p.g, 2), -1.5)*(2.0*ay*(ax*ax + std::pow(az + m_p.g, 2))*(ax*jx + jz*(az + m_p.g))*(ax*jx + ay*jy + jz*(az + m_p.g)) - ay*(ax*ax + std::pow(az + m_p.g, 2))*(ax*ax + ay*ay + std::pow(az + m_p.g, 2))*(ax*sx + jx*jx + jz*jz + sz*(az + m_p.g)) + ay*std::pow(ax*jx + jz*(az + m_p.g), 2)*(ax*ax + ay*ay + std::pow(az + m_p.g, 2)) - 2.0*jy*std::pow(ax*ax + std::pow(az + m_p.g, 2), 2)*(ax*jx + ay*jy + jz*(az + m_p.g)) + sy*std::pow(ax*ax + std::pow(az + m_p.g, 2), 2)*(ax*ax + ay*ay + std::pow(az + m_p.g, 2)))/std::pow(ax*ax + ay*ay + std::pow(az + m_p.g, 2), 2);
    const double T3_ff        = m_p.Iz * r.yawAcc;   // yaw-torque FF = Iz * yawAcc

    // Build the LQR reference state s_ref; u_lqr = -K_e * (s - s_ref).
    StateVec s_ref{};
    s_ref[StateToIdx(StateName::X)]        = r.pos[0];
    s_ref[StateToIdx(StateName::Y)]        = r.pos[1];
    s_ref[StateToIdx(StateName::Z)]        = r.pos[2];
    s_ref[StateToIdx(StateName::Alpha)]    = alpha_ff;
    s_ref[StateToIdx(StateName::Beta)]     = beta_ff;
    s_ref[StateToIdx(StateName::Psi)]      = r.yaw;
    s_ref[StateToIdx(StateName::XDot)]     = r.vel[0];
    s_ref[StateToIdx(StateName::YDot)]     = r.vel[1];
    s_ref[StateToIdx(StateName::ZDot)]     = r.vel[2];
    s_ref[StateToIdx(StateName::AlphaDot)] = alpha_ff_dot;
    s_ref[StateToIdx(StateName::BetaDot)]  = beta_ff_dot;
    s_ref[StateToIdx(StateName::PsiDot)]   = r.yawRate;

    // Tracking error e = s - s_ref, with a heading wrap on the yaw error.
    // NOTE: unlike the quadrotor, NO yaw-frame rotation of the horizontal
    // errors is applied here — and none is needed. In Rm = Ry(a)*Rx(b)*Rz(psi)
    // the roll Rz is the innermost rotation and leaves body-z invariant, so
    // the thrust direction (and the isotropic lateral drag) do not depend on
    // psi: the plant is roll-invariant and the yaw=0 gain is valid at any psi.
    // Rotating the errors here would MIS-align the loop by psi (unstable
    // beyond ~0.8 rad; verified by closed-loop eigenvalues).
    std::array<double, 16> e{};
    for (std::size_t j = 0; j < 16; ++j) e[j] = s[j] - s_ref[j];
    { double dp = e[StateToIdx(StateName::Psi)];
      e[StateToIdx(StateName::Psi)] = std::atan2(std::sin(dp), std::cos(dp)); }

    // LQR correction: u_lqr = -m_K_e * e.
    InputVec u_lqr{};
    for (std::size_t i = 0; i < 4; ++i) {
        double v = 0.0;
        for (std::size_t j = 0; j < 16; ++j) {
            v += m_K_e[i][j] * e[j];
        }
        u_lqr[i] = -v;
    }

    // Total control: u = u_ff + u_lqr, then saturate actuators.
    InputVec u{};
    u[0] = F1_ff + u_lqr[0];
    u[1] = T1_ff + u_lqr[1];
    u[2] = T2_ff + u_lqr[2];
    u[3] = T3_ff + u_lqr[3];

    if      (u[0] > m_p.F1_max) { u[0] = m_p.F1_max; }
    else if (u[0] < m_p.F1_min) { u[0] = m_p.F1_min; }
    if      (u[1] > m_p.T1_max) { u[1] = m_p.T1_max; }
    else if (u[1] < m_p.T1_min) { u[1] = m_p.T1_min; }
    if      (u[2] > m_p.T2_max) { u[2] = m_p.T2_max; }
    else if (u[2] < m_p.T2_min) { u[2] = m_p.T2_min; }
    if      (u[3] > m_p.T3_max) { u[3] = m_p.T3_max; }
    else if (u[3] < m_p.T3_min) { u[3] = m_p.T3_min; }

    return u;
}

} }  // namespace CDS::Dynamics
