/* dynamics_rocket_ff_lqr_01.hpp -- generated by dynamics_rocket_FFLQR01.ipynb.
 * Author: Diego Perazzolo. Do not edit by hand.
 */
#pragma once
#include <array>
#include <cstddef>
#ifdef JUST_TESTING_DYNAMICS
#include "test_core_defs.hpp"
#else
#include "core_defs.hpp"
#endif

namespace CDS { namespace Dynamics {

class ROCKET_FF_LQR_01 {
public:
    using StateVec = std::array<double, 16>;
    using InputVec = std::array<double, 4>;

    enum class StateName : std::size_t {
        X = 0,
        Y = 1,
        Z = 2,
        Alpha = 3,
        Beta = 4,
        Psi = 5,
        XDot = 6,
        YDot = 7,
        ZDot = 8,
        AlphaDot = 9,
        BetaDot = 10,
        PsiDot = 11,
        IntX = 12,
        IntY = 13,
        IntZ = 14,
        IntPsi = 15,
    };
    enum class ParamName : std::size_t {
        Mass = 0,
        Ix = 1,
        Iy = 2,
        Iz = 3,
        Gravity = 4,
        DragLateral = 5,
        DragAxial = 6,
        ThrustMax = 7,
        ThrustMin = 8,
        TorqueXMax = 9,
        TorqueXMin = 10,
        TorqueYMax = 11,
        TorqueYMin = 12,
        TorqueZMax = 13,
        TorqueZMin = 14,
    };

    ROCKET_FF_LQR_01();
    InputVec ExecuteControl(const StateVec& s, const Reference_t& r) const;
    StateVec Dynamics(const StateVec& s, const InputVec& u,
                      const Reference_t& ref, const Vec3& userF) const;
    static double GetState(const StateVec& s, StateName n);
    static void   SetState(StateVec& s, StateName n, double v);
    double GetParam(ParamName n) const;
    void   SetParam(ParamName n, double v);
    static constexpr std::size_t StateToIdx(StateName n) noexcept { return static_cast<std::size_t>(n); }

    // LQR error dynamics (A_e, B_e) and default weights (Q, R) at the nominal
    // operating point, plus the default/reference gain -- all constant, emitted
    // by codegen. The runtime re-synthesises the gain from these (CDS::control::lqr,
    // e.g. after retuning Q, R) and installs it with SetGain; A_e, B_e stay fixed.
    static const double A_e[16][16];
    static const double B_e[16][4];
    static const double Q_default[16][16];
    static const double R_default[4][4];
    static const double K_default[4][16];
    void SetGain(const double (&K)[4][16]);

private:
    struct PhysicsParams {
            double m = 10.0;  // vehicle mass [kg]
            double Ix = 3.3333333333333335;  // inertia around body x [kg m^2]
            double Iy = 3.3333333333333335;  // inertia around body y [kg m^2]
            double Iz = 1.0;  // inertia around body z [kg m^2]
            double g = 9.81;  // gravity [m/s^2]
            double c = 1.0;  // lateral drag coeff (body x, y) [N s/m]
            double cz = 0.02;  // axial drag coeff (body z) [N s/m]
            double F1_max = 500.0;  // thrust upper saturation [N]
            double F1_min = 0.0;  // thrust lower saturation [N]
            double T1_max = 10;  // Torque T1, about body y axis (drives alpha), upper saturation [Nm]
            double T1_min = -10;  // Torque T1, about body y axis (drives alpha), lower saturation [Nm]
            double T2_max = 10;  // Torque T2, about body x axis (drives beta), upper saturation [Nm]
            double T2_min = -10;  // Torque T2, about body x axis (drives beta), lower saturation [Nm]
            double T3_max = 10;  // Torque T3, about body z axis (drives psi), upper saturation [Nm]
            double T3_min = -10;  // Torque T3, about body z axis (drives psi), lower saturation [Nm]
    };
    PhysicsParams m_p;
    double m_K_e[4][16];   // active LQR gain (default K_default; SetGain overrides)
};

} }  // namespace CDS::Dynamics
