// =============================================================================
// Controlled Descent Simulator
// =============================================================================
//
// Copyright (c) 2026 Diego Perazzolo
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//
// =============================================================================
// File        : ext_comm.hpp
// Description : External communication API (ext ↔ core adapter layer).
//               Contract implemented by every adapter: ext_comm.cpp calls the
//               core directly (wasm-only, ws-served server), ext_comm_ws.cpp
//               forwards over WebSocket (ws-served client).
// Author      : Diego Perazzolo
// Created     : 2026
// GENERATED by apps/common/gen_ext.py from apps/common/ext_api.py — DO NOT EDIT BY HAND
// =============================================================================
#pragma once
#include "ext_defs.hpp"

/* structs */

/* params for initializing rocket model */
typedef struct
{
    ext_rocketParams params;
    ext_rocketActuatorLimits actuatorLimits;
} ext_initRocketParams;

/* params for initializing quadRotor model */
typedef struct
{
    ext_quadRotorParams params;
    ext_quadRotorActuatorLimits actuatorLimits;
} ext_initQuadRotorParams;

/* struct of the argument of setSystemParams */
typedef struct
{
    ext_coord_t timestep_seconds;
    ext_userForce user_forces;
} ext_systemParams;

/* struct of the returned data from getSnapshot */
typedef struct
{
    /* elapsed simulation time */
    ext_coord_t time_seconds;
    ext_fullState state;
    ext_setpointError err;
    bool isError;
} ext_snapshotData;

/* struct of the returned data from getPlantSnapshot */
typedef struct
{
    /* plant-side time of the last sample */
    ext_coord_t time_seconds;
    /* sequence number of the last sample, exact as a
       float up to 2^24 samples (~93 h at 50 Hz) */
    ext_coord_t sequence;
    ext_fullState state;
    bool isAttached;
    /* the plant is ready for a mission (staged / no staging needed) */
    bool isReadyToStart;
    bool isError;
} ext_plantSnapshotData;

/* struct of a batch of recent log lines. `lines` packs `count`
newline-separated records, each 'LEVEL\tmodule\ttext'; the JS side
splits on '\n' then on '\t'. Fixed char buffer: text on the POD wire */
typedef struct
{
    char lines[3800];
    /* number of records packed in `lines` */
    ext_coord_t count;
    /* lines dropped since the last batch (UI buffer overflow) */
    ext_coord_t dropped;
} ext_logBatch;

/* struct listing registered modules, one 'index\tname\tvalue' record
per newline; `value` is the log level (getLogModules) or the enabled
flag 0/1 (getProfileModules). Fixed char buffer: text on the POD wire */
typedef struct
{
    char list[1200];
    /* number of modules listed in `list` */
    ext_coord_t count;
} ext_moduleList;

/* struct of the profiler stats table, one record per newline:
'module\tscope\tcount\tmean_us\tmin_us\tmax_us\tstd_us'. Fixed char
buffer: text on the POD wire */
typedef struct
{
    char table[3600];
    /* number of scope records in `table` */
    ext_coord_t count;
} ext_profileTable;

/* request: set a log module's runtime level and sampling divisor N
(module as its index; N = 1 emits all, N>1 emits 1 in N per _SAMPLED
call site) */
typedef struct
{
    ext_coord_t module;
    ext_coord_t level;
    ext_coord_t sampleN;
} ext_logLevelParams;

/* request: enable or disable profiling for a module (module as its index) */
typedef struct
{
    ext_coord_t module;
    bool enabled;
} ext_profileEnableParams;

/* request: toggle the server-side diagnostics files (no-op on wasm,
which has no real filesystem). logFile: mirror the log to a file;
profileRaw: stream every raw profiler sample to a CSV for analysis */
typedef struct
{
    bool logFile;
    bool profileRaw;
} ext_diagFiles;

/* request: toggle the server-side per-tick data recorder — a lossless
wide-CSV black box of the active model's state/input/reference/error
(no-op on wasm, which has no real filesystem) */
typedef struct
{
    bool enabled;
} ext_recordParams;

/* response: state of the data recorder. modelName is the active
recorder's name (empty if no model is running). active/enabled/
droppedRows are carried as ext_coord_t (not bool) so this response
shares no wire struct with a bool while still holding a char buffer.
droppedRows is exact up to 2^24 rows (float mantissa) */
typedef struct
{
    char modelName[64];
    ext_coord_t active; // 1.0 if a model recorder is registered, else 0.0
    ext_coord_t enabled; // 1.0 if it is currently recording, else 0.0
    /* rows lost to a full ring since the run began */
    ext_coord_t droppedRows;
} ext_recordStatus;

/* response: the active controller's exposed parameters, one record per
newline: 'id\tgroup\tlabel\tflags\tvalue' (flags = 'rw' | 'ro').
Fixed char buffer: text on the POD wire (empty if no tunable params) */
typedef struct
{
    char text[2048];
} ext_controllerManifest;

/* request: set one controller parameter by its manifest id. id is
carried as ext_coord_t (exact up to 2^24) since the wire has no int */
typedef struct
{
    /* parameter id = its row index in the manifest */
    ext_coord_t id;
    /* new value for the parameter */
    ext_coord_t value;
} ext_controllerParamSet;

/* Initialize Rocket model: FF_LQR_01, returns true on error */
bool ext_initRocket_FFLQR01(ext_initRocketParams params);

/* Initialize QuadRotor model: FF_LQR_01, returns true on error */
bool ext_initQuadRotor_FFLQR01(ext_initQuadRotorParams params);

/* Get a point at time instant t along the trajectory */
ext_trajectoryPoint ext_trajectory_get_point(ext_coord_t t);

/* Add a trajectory Polynomial 4th order, returns true on error */
bool ext_trajectory_append_poly4(ext_trajectoryPoly4Params_t params);

/* Add a trajectory Point, returns true on error */
bool ext_trajectory_append_point(ext_trajectoryPointParams_t params);

/* Remove last trajectory item, returns true on error */
bool ext_trajectory_remove_last_item(void);

/* Set timestep and user forces */
bool ext_setSystemParams(ext_systemParams params);

/* Get simulation's time, model's state and tracking error */
ext_snapshotData ext_getSnapshot(void);

/* Run simulation / plant ticking */
bool ext_run(void);

/* Stop simulation / plant ticking */
bool ext_stop(void);

/* Get the plant's last sample: plant time, sequence and state */
ext_plantSnapshotData ext_getPlantSnapshot(void);

/* Auto-stage the plant to (trajectory vertical range + safetyAltitude, m) */
bool ext_beginStaging(ext_coord_t safetyAltitude);

/* Abort auto-staging (hold in place) */
bool ext_stopStaging(void);

/* Initialize QuadRotor model: MPC_01 (nonlinear MPC), returns true on error */
bool ext_initQuadRotor_MPC01(ext_initQuadRotorParams params);

/* Drain a batch of recent log lines from the UI buffer */
ext_logBatch ext_getLogBatch(void);

/* List the registered log modules with their current level */
ext_moduleList ext_getLogModules(void);

/* Set a log module's runtime level, returns true on error */
bool ext_setLogLevel(ext_logLevelParams params);

/* List the registered profiler modules with their enabled flag */
ext_moduleList ext_getProfileModules(void);

/* Enable or disable profiling for a module, returns true on error */
bool ext_setProfileEnabled(ext_profileEnableParams params);

/* Get the profiler stats table from the latest published snapshot */
ext_profileTable ext_getProfileTable(void);

/* Reset all profiler statistics (clears cold-start outliers), returns true on error */
bool ext_resetProfile(void);

/* Toggle server-side log-to-file and raw-profiler-CSV, returns true on error */
bool ext_setDiagFiles(ext_diagFiles params);

/* Toggle the per-tick data recorder; returns the recorder status */
ext_recordStatus ext_setRecording(ext_recordParams params);

/* Get the data recorder status (active model, enabled flag, dropped rows) */
ext_recordStatus ext_getRecordStatus(void);

/* Get the active controller's parameter manifest (TSV listing) */
ext_controllerManifest ext_getControllerManifest(void);

/* Set one controller parameter by its manifest id; returns true on error */
bool ext_setControllerParam(ext_controllerParamSet params);
