// =============================================================================
// Controlled Descent Simulator
// =============================================================================
//
// Copyright (c) 2026 Diego Perazzolo
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//
// =============================================================================
// File        : ext_comm.hpp
// Description : External communication API (ext ↔ core adapter layer).
//               Contract implemented by every adapter: ext_comm.cpp calls the
//               core directly (wasm-only, ws-served server), ext_comm_ws.cpp
//               forwards over WebSocket (ws-served client).
// Author      : Diego Perazzolo
// Created     : 2026
// GENERATED by apps/common/gen_ext.py from apps/common/ext_api.py — DO NOT EDIT BY HAND
// =============================================================================
#pragma once
#include "ext_defs.hpp"

/* structs */

/* params for initializing rocket model */
typedef struct
{
    ext_rocketParams params;
    ext_rocketActuatorLimits actuatorLimits;
} ext_initRocketParams;

/* params for initializing quadRotor model */
typedef struct
{
    ext_quadRotorParams params;
    ext_quadRotorActuatorLimits actuatorLimits;
} ext_initQuadRotorParams;

/* struct of the argument of setSystemParams */
typedef struct
{
    ext_coord_t timestep_seconds;
    ext_userForce user_forces;
} ext_systemParams;

/* struct of the returned data from getSnapshot */
typedef struct
{
    /* elapsed simulation time */
    ext_coord_t time_seconds;
    ext_fullState state;
    ext_setpointError err;
    bool isError;
} ext_snapshotData;

/* struct of the returned data from getPlantSnapshot */
typedef struct
{
    /* plant-side time of the last sample */
    ext_coord_t time_seconds;
    /* sequence number of the last sample, exact as a
       float up to 2^24 samples (~93 h at 50 Hz) */
    ext_coord_t sequence;
    ext_fullState state;
    bool isAttached;
    /* the plant is ready for a mission (staged / no staging needed) */
    bool isReadyToStart;
    bool isError;
} ext_plantSnapshotData;

/* Initialize Rocket model: FF_LQR_01, returns true on error */
bool ext_initRocket_FFLQR01(ext_initRocketParams params);

/* Initialize QuadRotor model: FF_LQR_01, returns true on error */
bool ext_initQuadRotor_FFLQR01(ext_initQuadRotorParams params);

/* Get a point at time instant t along the trajectory */
ext_trajectoryPoint ext_trajectory_get_point(ext_coord_t t);

/* Add a trajectory Polynomial 4th order, returns true on error */
bool ext_trajectory_append_poly4(ext_trajectoryPoly4Params_t params);

/* Add a trajectory Point, returns true on error */
bool ext_trajectory_append_point(ext_trajectoryPointParams_t params);

/* Remove last trajectory item, returns true on error */
bool ext_trajectory_remove_last_item(void);

/* Set timestep and user forces */
bool ext_setSystemParams(ext_systemParams params);

/* Get simulation's time, model's state and tracking error */
ext_snapshotData ext_getSnapshot(void);

/* Run simulation / plant ticking */
bool ext_run(void);

/* Stop simulation / plant ticking */
bool ext_stop(void);

/* Get the plant's last sample: plant time, sequence and state */
ext_plantSnapshotData ext_getPlantSnapshot(void);

/* Auto-stage the plant to (trajectory vertical range + safetyAltitude, m) */
bool ext_beginStaging(ext_coord_t safetyAltitude);

/* Abort auto-staging (hold in place) */
bool ext_stopStaging(void);

/* Initialize QuadRotor model: MPC_01 (nonlinear MPC), returns true on error */
bool ext_initQuadRotor_MPC01(ext_initQuadRotorParams params);
