/* dynamics_quadrotor_mpc_01.hpp -- generated by dynamics_quadRotor_MPC01.ipynb.
 * Author: Diego Perazzolo. Do not edit by hand.
 * MPC prediction model: dynamics f(x,u) + Jacobians f_x, f_u. No control law.
 */
#pragma once
#include <array>
#include <cstddef>

namespace CDS { namespace Dynamics {

class QUADROTOR_MPC_01 {
public:
    static constexpr std::size_t STATE_DIM = 13;
    static constexpr std::size_t INPUT_DIM = 4;
    using StateVec   = std::array<double, STATE_DIM>;
    using InputVec   = std::array<double, INPUT_DIM>;
    using UserForces = std::array<double, 3>;

    enum class StateName : std::size_t {
        X = 0,
        Y = 1,
        Z = 2,
        Qw = 3,
        Qx = 4,
        Qy = 5,
        Qz = 6,
        VX = 7,
        VY = 8,
        VZ = 9,
        WX = 10,
        WY = 11,
        WZ = 12,
    };
    enum class ParamName : std::size_t {
        Mass = 0,
        Ix = 1,
        Iy = 2,
        Iz = 3,
        Gravity = 4,
        DragX = 5,
        DragY = 6,
        DragZ = 7,
        KThrust = 8,
        KTorque = 9,
        Arm = 10,
        ThrustMax = 11,
        ThrustMin = 12,
    };

    QUADROTOR_MPC_01();

    // State derivative dx/dt = f(x, u) + world-frame external force userF.
    StateVec Dynamics(const StateVec& s, const InputVec& u, const UserForces& userF) const;
    // Jacobians of f at (x,u): fx = df/dx (STATE x STATE), fu = df/du (STATE x INPUT).
    // userF is additive, so it does not enter the Jacobians.
    void Jacobians(const StateVec& s, const InputVec& u,
                   double fx[STATE_DIM][STATE_DIM], double fu[STATE_DIM][INPUT_DIM]) const;

    static double GetState(const StateVec& s, StateName n);
    static void   SetState(StateVec& s, StateName n, double v);
    double GetParam(ParamName n) const;
    void   SetParam(ParamName n, double v);
    static constexpr std::size_t StateToIdx(StateName n) noexcept { return static_cast<std::size_t>(n); }

private:
    struct PhysicsParams {
            double m = 2.4;  // vehicle mass [kg]
            double Ix = 0.025;  // inertia x [kg m^2]
            double Iy = 0.025;  // inertia y [kg m^2]
            double Iz = 0.045;  // inertia z [kg m^2]
            double g = 9.81;  // gravity [m/s^2]
            double dx = 0.2;  // world drag x
            double dy = 0.2;  // world drag y
            double dz = 0.3;  // world drag z
            double kT = 1e-05;  // thrust coeff kT
            double kQ = 1.6e-07;  // torque coeff kQ
            double L = 0.275;  // arm length [m]
            double T_max = 36.0;  // per-rotor thrust max [N]
            double T_min = 0.0;  // per-rotor thrust min [N]
    };
    PhysicsParams m_p;
};

} }  // namespace CDS::Dynamics
