/* dynamics_quadrotor_ff_lqr_01.cpp -- generated by dynamics_quadRotor_FFLQR01.ipynb.
 * Author: Diego Perazzolo. Do not edit by hand.
 */
#include "dynamics_quadrotor_ff_lqr_01.hpp"
#include <cmath>
#include <algorithm>

namespace CDS { namespace Dynamics {

const double QUADROTOR_FF_LQR_01::A_e[16][16] = {
    {0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0},
    {0, 0, 0, 0, 9.8100000000000005, 0, -0.083333333333333343, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, -9.8100000000000005, 0, 0, 0, -0.083333333333333343, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, -0.125, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {-1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, -1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, -1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, -1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
};

const double QUADROTOR_FF_LQR_01::B_e[16][4] = {
    {0, 0, 0, 0},
    {0, 0, 0, 0},
    {0, 0, 0, 0},
    {0, 0, 0, 0},
    {0, 0, 0, 0},
    {0, 0, 0, 0},
    {0, 0, 0, 0},
    {0, 0, 0, 0},
    {0.41666666666666669, 0, 0, 0},
    {0, 40.0, 0, 0},
    {0, 0, 40.0, 0},
    {0, 0, 0, 22.222222222222221},
    {0, 0, 0, 0},
    {0, 0, 0, 0},
    {0, 0, 0, 0},
    {0, 0, 0, 0}
};

const double QUADROTOR_FF_LQR_01::Q_default[16][16] = {
    {1200.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 1200.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 1200.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 120.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 120.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 200.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 2.0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 2.0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 2.0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 80.0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 80.0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 80.0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40.0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40.0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40.0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40.0}
};

const double QUADROTOR_FF_LQR_01::R_default[4][4] = {
    {0.01, 0, 0, 0},
    {0, 4.0, 0, 0},
    {0, 0, 4.0, 0},
    {0, 0, 0, 4.0}
};

const double QUADROTOR_FF_LQR_01::K_default[4][16] = {
    {-9.2327077700235082e-13, 2.58028788759796e-12, 354.28031489305687, -3.0293863333223653e-12, 7.1653633513958651e-13, -1.6985834035606011e-14, -2.5769468509512799e-14, 6.7253113301119062e-13, 43.296278642639599, -1.2213304750696756e-14, 8.8454032489866537e-15, 2.0284939132551746e-15, 1.9848180331670515e-13, -9.4887616405905481e-13, -63.245553203368097, -1.4709758441148104e-13},
    {-2.162811634309552e-13, -19.244600234962807, 2.5272592593104954e-14, 31.788210558657983, 4.3561760986291476e-14, 7.4358921797745861e-14, 5.2858346110599223e-15, -10.85401266432758, -2.9311931401672208e-15, 4.6464406299804342, -1.4325121418141857e-15, -2.3492411173286085e-16, -6.300025675148089e-14, 3.1622776601686997, 2.3839437368611335e-14, -3.5184939176270536e-14},
    {19.244600234962171, -2.8532731732866523e-13, -2.2816924906975303e-14, 4.2632564145606011e-13, 31.788210558656516, 5.7347272556264752e-15, 10.854012664327019, -3.7254975168543934e-17, 2.122896779756797e-15, -1.4325121418141857e-15, 4.6464406299804182, 4.3801754251440166e-16, -3.1622776601683711, -7.1037915535631351e-14, -2.6429315510187135e-15, -6.8851097291673702e-16},
    {-6.2787703809042056e-14, 2.5772313912789218e-13, -1.3822119589047422e-14, -1.0466523853550145e-13, 4.484407163554796e-14, 8.8794041644163464, -5.9377318929581247e-16, 6.9138515294938437e-14, 2.704658551006899e-16, -1.3051339540714492e-16, 2.4334307917466755e-16, 4.5606081145826884, 2.5113438864475986e-14, -3.971264057984064e-14, -3.5808310764069556e-15, -3.1622776601683937}
};

QUADROTOR_FF_LQR_01::QUADROTOR_FF_LQR_01()
{
    for (std::size_t i = 0; i < 4; ++i)
        for (std::size_t j = 0; j < 16; ++j) m_K_e[i][j] = K_default[i][j];
}

void QUADROTOR_FF_LQR_01::SetGain(const double (&K)[4][16])
{
    for (std::size_t i = 0; i < 4; ++i)
        for (std::size_t j = 0; j < 16; ++j) m_K_e[i][j] = K[i][j];
}

double QUADROTOR_FF_LQR_01::GetState(const StateVec& s, StateName n) {
    switch (n) {
        case StateName::X: return s[0];
        case StateName::Y: return s[1];
        case StateName::Z: return s[2];
        case StateName::Qw: return s[3];
        case StateName::Qx: return s[4];
        case StateName::Qy: return s[5];
        case StateName::Qz: return s[6];
        case StateName::VX: return s[7];
        case StateName::VY: return s[8];
        case StateName::VZ: return s[9];
        case StateName::WX: return s[10];
        case StateName::WY: return s[11];
        case StateName::WZ: return s[12];
        case StateName::IntX: return s[13];
        case StateName::IntY: return s[14];
        case StateName::IntZ: return s[15];
        case StateName::IntPsi: return s[16];
    }
    return 0.0;
}
void QUADROTOR_FF_LQR_01::SetState(StateVec& s, StateName n, double v) {
    switch (n) {
        case StateName::X: s[0] = v; return;
        case StateName::Y: s[1] = v; return;
        case StateName::Z: s[2] = v; return;
        case StateName::Qw: s[3] = v; return;
        case StateName::Qx: s[4] = v; return;
        case StateName::Qy: s[5] = v; return;
        case StateName::Qz: s[6] = v; return;
        case StateName::VX: s[7] = v; return;
        case StateName::VY: s[8] = v; return;
        case StateName::VZ: s[9] = v; return;
        case StateName::WX: s[10] = v; return;
        case StateName::WY: s[11] = v; return;
        case StateName::WZ: s[12] = v; return;
        case StateName::IntX: s[13] = v; return;
        case StateName::IntY: s[14] = v; return;
        case StateName::IntZ: s[15] = v; return;
        case StateName::IntPsi: s[16] = v; return;
    }
}
double QUADROTOR_FF_LQR_01::GetParam(ParamName n) const {
    switch (n) {
        case ParamName::Mass: return m_p.m;
        case ParamName::Ix: return m_p.Ix;
        case ParamName::Iy: return m_p.Iy;
        case ParamName::Iz: return m_p.Iz;
        case ParamName::Gravity: return m_p.g;
        case ParamName::DragLat: return m_p.c;
        case ParamName::DragAx: return m_p.cz;
        case ParamName::KThrust: return m_p.kT;
        case ParamName::KTorque: return m_p.kQ;
        case ParamName::Arm: return m_p.L;
        case ParamName::IRotor: return m_p.Irot;
        case ParamName::ThrustMax: return m_p.T_max;
        case ParamName::ThrustMin: return m_p.T_min;
    }
    return 0.0;
}
void QUADROTOR_FF_LQR_01::SetParam(ParamName n, double v) {
    switch (n) {
        case ParamName::Mass: m_p.m = v; return;
        case ParamName::Ix: m_p.Ix = v; return;
        case ParamName::Iy: m_p.Iy = v; return;
        case ParamName::Iz: m_p.Iz = v; return;
        case ParamName::Gravity: m_p.g = v; return;
        case ParamName::DragLat: m_p.c = v; return;
        case ParamName::DragAx: m_p.cz = v; return;
        case ParamName::KThrust: m_p.kT = v; return;
        case ParamName::KTorque: m_p.kQ = v; return;
        case ParamName::Arm: m_p.L = v; return;
        case ParamName::IRotor: m_p.Irot = v; return;
        case ParamName::ThrustMax: m_p.T_max = v; return;
        case ParamName::ThrustMin: m_p.T_min = v; return;
    }
}

QUADROTOR_FF_LQR_01::StateVec QUADROTOR_FF_LQR_01::Dynamics(const StateVec& s, const InputVec& u,
                                       const Reference_t& ref, const std::array<double, 3>& userF) const
{
    const double r_x = s[0];
    const double r_y = s[1];
    const double r_z = s[2];
    const double q_w = s[3];
    const double q_x = s[4];
    const double q_y = s[5];
    const double q_z = s[6];
    const double v_x = s[7];
    const double v_y = s[8];
    const double v_z = s[9];
    const double w_x = s[10];
    const double w_y = s[11];
    const double w_z = s[12];
    const double ix = s[13];
    const double iy = s[14];
    const double iz = s[15];
    const double ipsi = s[16];
    const double T1 = u[0];
    const double T2 = u[1];
    const double T3 = u[2];
    const double T4 = u[3];
    const double refx = ref.pos[0];
    const double refy = ref.pos[1];
    const double refz = ref.pos[2];
    const double ref_yaw = ref.yaw;
    const double user_fX = userF[0];
    const double user_fY = userF[1];
    const double user_fZ = userF[2];

    StateVec dxdt{};
    const double cse0 = 1.0/m_p.m;
    const double cse1 = T1 + T2 + T3 + T4;
    const double cse2 = q_w*q_y;
    const double cse3 = q_x*q_z;
    const double cse4 = cse2 + cse3;
    const double cse5 = 2.0*cse4;
    const double cse6 = q_w*q_x;
    const double cse7 = q_y*q_z;
    const double cse8 = cse6 - cse7;
    const double cse9 = 2.0*pow(q_x, 2);
    const double cse10 = 2.0*pow(q_y, 2) - 1.0;
    const double cse11 = cse10 + cse9;
    const double cse12 = -cse11*v_z + 2.0*cse4*v_x - 2.0*cse8*v_y;
    const double cse13 = m_p.cz*cse12;
    const double cse14 = q_w*q_z;
    const double cse15 = q_x*q_y;
    const double cse16 = 2.0*cse14 - 2.0*cse15;
    const double cse17 = cse6 + cse7;
    const double cse18 = 2.0*pow(q_z, 2);
    const double cse19 = cse18 + cse9 - 1.0;
    const double cse20 = m_p.c*(-cse16*v_x + 2.0*cse17*v_z - cse19*v_y);
    const double cse21 = cse10 + cse18;
    const double cse22 = cse14 + cse15;
    const double cse23 = cse2 - cse3;
    const double cse24 = -cse21*v_x + 2.0*cse22*v_y - 2.0*cse23*v_z;
    const double cse25 = m_p.c*cse24;
    const double cse26 = 2.0*cse8;
    const double cse27 = w_y*w_z;
    const double cse28 = 0.70710678118654752*m_p.L;
    const double cse29 = T1*cse28;
    const double cse30 = T2*cse28;
    const double cse31 = m_p.Irot*pow(m_p.kT, -0.5)*(sqrt(fabs(T1))*(((T1) > 0) - ((T1) < 0)) + sqrt(fabs(T2))*(((T2) > 0) - ((T2) < 0)) - sqrt(fabs(T3))*(((T3) > 0) - ((T3) < 0)) - sqrt(fabs(T4))*(((T4) > 0) - ((T4) < 0)));
    const double cse32 = -T3*cse28 + T4*cse28;
    const double cse33 = w_x*w_z;
    const double cse34 = w_x*w_y;
    const double cse35 = m_p.kQ/m_p.kT;
    const double cse36 = ref_yaw - atan2(2*cse22, -cse21);
    dxdt[0] = v_x;
    dxdt[1] = v_y;
    dxdt[2] = v_z;
    dxdt[3] = -0.5*q_x*w_x - 0.5*q_y*w_y - 0.5*q_z*w_z;
    dxdt[4] = 0.5*q_w*w_x + 0.5*q_y*w_z - 0.5*q_z*w_y;
    dxdt[5] = 0.5*q_w*w_y - 0.5*q_x*w_z + 0.5*q_z*w_x;
    dxdt[6] = 0.5*q_w*w_z + 0.5*q_x*w_y - 0.5*q_y*w_x;
    dxdt[7] = cse0*(cse1*cse5 - cse13*cse5 + cse16*cse20 + cse21*cse25 + user_fX);
    dxdt[8] = cse0*(-cse1*cse26 + cse13*cse26 + cse19*cse20 - 2.0*cse22*cse25 + user_fY);
    dxdt[9] = cse0*(2.0*m_p.c*cse23*cse24 + m_p.cz*cse11*cse12 - m_p.g*m_p.m - cse1*cse11 - 2.0*cse17*cse20 + user_fZ);
    dxdt[10] = -(-m_p.Iy*cse27 + m_p.Iz*cse27 + cse29 - cse30 + cse31*w_y + cse32)/m_p.Ix;
    dxdt[11] = (-m_p.Ix*cse33 + m_p.Iz*cse33 - cse29 + cse30 + cse31*w_x + cse32)/m_p.Iy;
    dxdt[12] = (m_p.Ix*cse34 - m_p.Iy*cse34 - T1*cse35 - T2*cse35 + T3*cse35 + T4*cse35)/m_p.Iz;
    dxdt[13] = -r_x + refx;
    dxdt[14] = -r_y + refy;
    dxdt[15] = -r_z + refz;
    dxdt[16] = ((pow(cse21, 2) + 4*pow(cse22, 2) < 9.9999999999999995e-7) ? (
   0
)
: (
   atan2(sin(cse36), cos(cse36))
));
    return dxdt;
}

QUADROTOR_FF_LQR_01::InputVec QUADROTOR_FF_LQR_01::ExecuteControl(const StateVec& s, const Reference_t& r) const
{
    // Flatness FF divides by ||a + g z_w||: clamp a_z away from free-fall
    // (a_z <= -g with a_x=a_y=0 would make z_B undefined). Trajectories
    // demanding > 1 g downward acceleration are out of the envelope.
    const double a_x=r.acc[0], a_y=r.acc[1];
    const double a_z=std::max(r.acc[2], -m_p.g + 1e-6);
    const double j_x=r.jerk[0], j_y=r.jerk[1], j_z=r.jerk[2];
    const double s_x=r.snap[0], s_y=r.snap[1], s_z=r.snap[2];
    const double psi=r.yaw, psi_dot=r.yawRate, psi_ddot=r.yawAcc;

    const double cse0 = m_p.g + a_z;
    const double cse1 = pow(cse0, 2);
    const double cse2 = pow(a_x, 2) + pow(a_y, 2) + cse1;
    const double cse3 = sqrt(cse2);
    const double cse4 = cos(psi);
    const double cse5 = sin(psi);
    const double cse6 = a_x*cse5;
    const double cse7 = a_y*cse4;
    const double cse8 = cse6 - cse7;
    const double cse9 = a_y*cse8;
    const double cse10 = -cse1*cse4 + cse9;
    const double cse11 = 1.0/cse3;
    const double cse12 = pow(cse5, 2);
    const double cse13 = cse1*cse12;
    const double cse14 = pow(cse4, 2);
    const double cse15 = cse1*cse14;
    const double cse16 = cse13 + cse15 + pow(cse8, 2);
    const double cse17 = pow(cse16, -0.5);
    const double cse18 = cse11*cse17;
    const double cse19 = cse0*cse17;
    const double cse20 = cse1*cse5;
    const double cse21 = a_x*cse8;
    const double cse22 = cse20 + cse21;
    const double cse23 = a_x*cse4;
    const double cse24 = a_y*cse5;
    const double cse25 = cse23 + cse24;
    const double cse26 = cse0*cse11;
    const double cse27 = cse4*j_z;
    const double cse28 = cse0*psi_dot;
    const double cse29 = cse28*cse5;
    const double cse30 = 1.0/cse2;
    const double cse31 = cse0*j_z;
    const double cse32 = a_x*j_x + a_y*j_y + cse31;
    const double cse33 = cse30*cse32;
    const double cse34 = cse0*cse33;
    const double cse35 = cse34*cse4;
    const double cse36 = cse0*cse4;
    const double cse37 = 1.0/cse16;
    const double cse38 = cse12*cse31;
    const double cse39 = cse14*cse31;
    const double cse40 = cse5*j_x;
    const double cse41 = cse4*j_y;
    const double cse42 = cse23*psi_dot;
    const double cse43 = cse24*psi_dot;
    const double cse44 = cse33*cse7;
    const double cse45 = cse33*cse6;
    const double cse46 = cse40 - cse41 + cse42 + cse43 + cse44 - cse45;
    const double cse47 = -cse13*cse33 - cse15*cse33 + cse38 + cse39 + cse46*cse8;
    const double cse48 = cse37*cse47;
    const double cse49 = cse36*cse48;
    const double cse50 = -cse27 + cse29 + cse35 + cse49;
    const double cse51 = cse5*j_z;
    const double cse52 = cse28*cse4;
    const double cse53 = cse34*cse5;
    const double cse54 = cse0*cse5;
    const double cse55 = cse48*cse54;
    const double cse56 = cse51 + cse52 - cse53 - cse55;
    const double cse57 = cse37*cse47*cse8 - cse46;
    const double cse58 = a_x*cse56 + a_y*cse50 + cse0*cse57;
    const double cse59 = -cse34 + j_z;
    const double cse60 = cse0*cse25;
    const double cse61 = -a_y*cse33 + j_y;
    const double cse62 = -a_x*cse33 + j_x;
    const double cse63 = cse10*cse62 - cse22*cse61 + cse59*cse60;
    const double cse64 = cse17*cse30;
    const double cse65 = cse0*cse48;
    const double cse66 = cse23*j_z;
    const double cse67 = cse24*j_z;
    const double cse68 = cse36*j_x;
    const double cse69 = cse54*j_y;
    const double cse70 = cse28*cse7;
    const double cse71 = cse28*cse6;
    const double cse72 = 2.0*cse34;
    const double cse73 = -cse23*cse72 - cse24*cse72 + cse66 + cse67 + cse68 + cse69 + cse70 - cse71;
    const double cse74 = 2.0*cse51;
    const double cse75 = cse1*cse4;
    const double cse76 = cse75*psi_dot;
    const double cse77 = cse8*j_x;
    const double cse78 = 2.0*cse33;
    const double cse79 = a_x*cse46;
    const double cse80 = -cse0*cse74 + cse20*cse48 + cse20*cse78 + cse21*cse33 + cse21*cse48 - cse76 - cse77 - cse79;
    const double cse81 = a_y*cse46;
    const double cse82 = cse8*j_y;
    const double cse83 = cse20*psi_dot;
    const double cse84 = 2.0*cse4;
    const double cse85 = cse33*cse9;
    const double cse86 = -cse31*cse84 + cse75*cse78 + cse81 + cse82 + cse83 - cse85;
    const double cse87 = cse0*cse5*(cse48*cse75 - cse48*cse9 + cse86) - cse36*cse80 - cse8*(-cse23*cse65 - cse24*cse65 + cse73);
    const double cse88 = cse11*cse37;
    const double cse89 = cse37*cse87;
    const double cse90 = cse30*cse63;
    const double cse91 = cse89*cse90;
    const double cse92 = pow(j_z, 2);
    const double cse93 = cse0*s_z;
    const double cse94 = 4.0*cse33;
    const double cse95 = pow(cse2, -2);
    const double cse96 = pow(cse32, 2);
    const double cse97 = cse95*cse96;
    const double cse98 = 4.0*cse97;
    const double cse99 = cse30*(a_x*s_x + a_y*s_y + cse92 + cse93 + pow(j_x, 2) + pow(j_y, 2));
    const double cse100 = 2.0*psi_dot;
    const double cse101 = pow(psi_dot, 2);
    const double cse102 = 3.0*cse97;
    const double cse103 = cse100*cse5*j_y - cse101*cse6 + cse101*cse7 + cse102*cse6 - cse102*cse7 + cse23*psi_ddot + cse24*psi_ddot - cse4*s_y - cse40*cse78 + cse41*cse78 - cse42*cse78 - cse43*cse78 + cse5*s_x - cse6*cse99 + cse7*cse99 + cse84*j_x*psi_dot;
    const double cse104 = cse103*cse8 + cse12*cse92 + cse12*cse93 + cse13*cse98 - cse13*cse99 + cse14*cse92 + cse14*cse93 + cse15*cse98 - cse15*cse99 - cse38*cse94 - cse39*cse94 + pow(cse46, 2);
    const double cse105 = pow(cse47, 2);
    const double cse106 = pow(cse16, -2);
    const double cse107 = 3.0*cse106;
    const double cse108 = cse105*cse107;
    const double cse109 = 2.0*cse27;
    const double cse110 = 2.0*cse48;
    const double cse111 = cse104*cse37;
    const double cse112 = cse0*cse99;
    const double cse113 = -cse47;
    const double cse114 = cse113*cse37;
    const double cse115 = cse0*cse114;
    const double cse116 = cse115*cse23 + cse115*cse24 + cse73;
    const double cse117 = cse114*cse75;
    const double cse118 = cse114*cse9 - cse117 + cse86;
    const double cse119 = -cse80;
    const double cse120 = cse100*j_z;
    const double cse121 = cse0*psi_ddot;
    const double cse122 = 2.0*cse28;
    const double cse123 = cse0*cse101;
    const double cse124 = 4.0*cse28;
    const double cse125 = 8.0*cse97;
    const double cse126 = cse0*cse125;
    const double cse127 = 2.0*cse112;
    const double cse128 = 2.0*cse114;
    const double cse129 = cse107*pow(cse113, 2);
    const double cse130 = cse0*cse129;
    const double cse131 = 4.0*cse114*cse34;
    const double cse132 = -cse104*cse37;
    const double cse133 = cse0*cse132;
    const double cse134 = 2.0*cse99;
    const double cse135 = 4.0*cse51;
    const double cse136 = cse31*cse4;
    const double F_ff = m_p.m*cse3;
    const double Rr00 = -cse10*cse18;
    const double Rr01 = -cse19*cse5;
    const double Rr02 = a_x*cse11;
    const double Rr10 = cse18*cse22;
    const double Rr11 = cse19*cse4;
    const double Rr12 = a_y*cse11;
    const double Rr20 = -cse17*cse25*cse26;
    const double Rr21 = cse17*cse8;
    const double Rr22 = cse26;
    const double wref_x = -cse18*cse58;
    const double wref_y = -cse63*cse64;
    const double wref_z = cse87*cse88;
    const double tff_x = cse18*(m_p.Ix*(a_x*cse30*cse32*cse56 - a_x*(3.0*cse0*cse105*cse106*cse5 + 2.0*cse0*cse30*cse32*cse37*cse47*cse5 + cse0*cse4*psi_ddot + 3.0*cse0*cse5*cse95*cse96 - cse101*cse54 - cse110*cse52 - cse111*cse54 - cse33*cse74 + 2.0*cse4*j_z*psi_dot - cse48*cse74 + cse5*s_z - cse52*cse78 - cse54*cse99) + a_y*cse30*cse32*cse50 - a_y*(cse101*cse36 - cse102*cse36 - cse108*cse36 + cse109*cse48 - cse110*cse29 - cse110*cse35 + cse111*cse36 + cse27*cse78 - cse29*cse78 + cse36*cse99 - cse4*s_z + cse54*psi_ddot + cse74*psi_dot) + cse0*cse30*cse32*cse57 - cse0*(-cse103 + cse104*cse37*cse8 - cse108*cse8 + 2.0*cse37*cse46*cse47) - cse50*j_y - cse56*j_x - cse57*j_z) + m_p.Iy*cse91 - m_p.Iz*cse91);
    const double tff_y = cse64*(-m_p.Ix*cse58*cse89 - m_p.Iy*(cse10*(3.0*a_x*cse95*cse96 - a_x*cse99 - cse78*j_x + s_x) + cse116*cse59 + cse118*cse62 - cse119*cse61 - cse22*(3.0*a_y*cse95*cse96 - a_y*cse99 - cse78*j_y + s_y) + cse60*(3.0*cse0*cse95*cse96 - cse112 - cse78*j_z + s_z)) + m_p.Iz*cse37*cse58*cse87);
    const double tff_z = cse88*(-m_p.Ix*cse58*cse90 + m_p.Iy*cse30*cse58*cse63 - m_p.Iz*(-cse116*cse37*cse47*cse8 + cse116*cse46 - cse118*cse51 - cse118*cse52 + cse118*cse53 + cse118*cse55 - cse119*cse27 + cse119*cse29 + cse119*cse35 + cse119*cse49 - cse36*(a_x*cse103 + 3.0*a_x*cse105*cse106*cse8 + 2.0*a_x*cse30*cse32*cse37*cse47*cse8 + 3.0*a_x*cse8*cse95*cse96 + 4.0*cse0*cse4*j_z*psi_dot + 2.0*cse0*cse5*s_z + 3.0*cse1*cse105*cse106*cse5 + 4.0*cse1*cse30*cse32*cse37*cse47*cse5 + cse1*cse4*psi_ddot + 8.0*cse1*cse5*cse95*cse96 - cse101*cse20 - cse110*cse76 - cse110*cse77 - cse110*cse79 - cse111*cse20 - cse111*cse21 - cse134*cse20 - cse135*cse65 - cse21*cse99 - 8.0*cse34*cse51 + 2.0*cse46*j_x + 2.0*cse5*cse92 - cse76*cse94 - cse77*cse78 - cse78*cse79 + cse8*s_x) - cse54*(a_y*cse103 + cse101*cse75 + cse102*cse9 - 4.0*cse114*cse136 + cse117*cse94 - cse125*cse75 + cse128*cse81 + cse128*cse82 + cse128*cse83 - cse128*cse85 - cse129*cse75 + cse129*cse9 - cse132*cse75 + cse132*cse9 + cse134*cse75 + cse135*cse28 + 8.0*cse136*cse33 + cse20*psi_ddot - 2.0*cse4*cse92 + 2.0*cse46*j_y - cse78*cse81 - cse78*cse82 + cse8*s_y - cse83*cse94 - cse84*cse93 - cse9*cse99) + cse8*(cse109*j_x - cse120*cse6 + cse120*cse7 - cse121*cse6 + cse121*cse7 - cse122*cse40 + cse122*cse41 - cse123*cse23 - cse123*cse24 - cse124*cse44 + cse124*cse45 + cse126*cse23 + cse126*cse24 - cse127*cse23 - cse127*cse24 + cse128*cse66 + cse128*cse67 + cse128*cse68 + cse128*cse69 + cse128*cse70 - cse128*cse71 + cse130*cse23 + cse130*cse24 - cse131*cse23 - cse131*cse24 + cse133*cse23 + cse133*cse24 + cse23*s_z + cse24*s_z - 4.0*cse35*j_x + cse36*s_x - 4.0*cse53*j_y + cse54*s_y - cse66*cse94 - cse67*cse94 + cse74*j_y)));

    const double qw=s[3], qx=s[4], qy=s[5], qz=s[6];
    const double Rc00=1-2*(qy*qy+qz*qz), Rc01=2*(qx*qy-qw*qz), Rc02=2*(qx*qz+qw*qy);
    const double Rc10=2*(qx*qy+qw*qz), Rc11=1-2*(qx*qx+qz*qz), Rc12=2*(qy*qz-qw*qx);
    const double Rc20=2*(qx*qz-qw*qy), Rc21=2*(qy*qz+qw*qx), Rc22=1-2*(qx*qx+qy*qy);

    const double Re00 = Rr00*Rc00 + Rr10*Rc10 + Rr20*Rc20;
    const double Re01 = Rr00*Rc01 + Rr10*Rc11 + Rr20*Rc21;
    const double Re02 = Rr00*Rc02 + Rr10*Rc12 + Rr20*Rc22;
    const double Re10 = Rr01*Rc00 + Rr11*Rc10 + Rr21*Rc20;
    const double Re11 = Rr01*Rc01 + Rr11*Rc11 + Rr21*Rc21;
    const double Re12 = Rr01*Rc02 + Rr11*Rc12 + Rr21*Rc22;
    const double Re20 = Rr02*Rc00 + Rr12*Rc10 + Rr22*Rc20;
    const double Re21 = Rr02*Rc01 + Rr12*Rc11 + Rr22*Rc21;
    const double Re22 = Rr02*Rc02 + Rr12*Rc12 + Rr22*Rc22;

    // dtheta = rotvec(R_ref^T R)  (exact; small-angle safe)
    const double cth = 0.5*(Re00+Re11+Re22-1.0);
    const double ex=Re21-Re12, ey=Re02-Re20, ez=Re10-Re01;
    const double s2 = std::sqrt(ex*ex+ey*ey+ez*ez);
    const double th = std::atan2(0.5*s2, cth);
    const double fac = (s2>1e-9)? th/s2 : 0.5;
    const double dth_x=fac*ex, dth_y=fac*ey, dth_z=fac*ez;

    // Yaw-frame compensation: the LQR gain was synthesized at yaw=0 (body-x = world-x).
    // At heading psi the horizontal position/velocity coupling is rotated by psi, so we
    // express the horizontal position, velocity and integral errors in the heading frame
    // (rotate by Rz(-psi)) before applying K. Without this the x/y loop slowly diverges as
    // psi grows (unstable beyond ~0.5 rad).
    const double cpsi = std::cos(psi), spsi = std::sin(psi);
    const double drx = s[0]-r.pos[0], dry = s[1]-r.pos[1];
    const double dvx = s[7]-r.vel[0], dvy = s[8]-r.vel[1];
    const double iix = s[13],          iiy = s[14];

    double err[16];
    err[0]= cpsi*drx + spsi*dry;  err[1]=-spsi*drx + cpsi*dry;  err[2]=s[2]-r.pos[2];
    err[3]=dth_x; err[4]=dth_y; err[5]=dth_z;
    err[6]= cpsi*dvx + spsi*dvy;  err[7]=-spsi*dvx + cpsi*dvy;  err[8]=s[9]-r.vel[2];
    err[9]=s[10]-wref_x; err[10]=s[11]-wref_y; err[11]=s[12]-wref_z;
    err[12]= cpsi*iix + spsi*iiy; err[13]=-spsi*iix + cpsi*iiy; err[14]=s[15]; err[15]=s[16];

    const double u_F = -(m_K_e[0][0]*err[0]+m_K_e[0][1]*err[1]+m_K_e[0][2]*err[2]+m_K_e[0][3]*err[3]+m_K_e[0][4]*err[4]+m_K_e[0][5]*err[5]+m_K_e[0][6]*err[6]+m_K_e[0][7]*err[7]+m_K_e[0][8]*err[8]+m_K_e[0][9]*err[9]+m_K_e[0][10]*err[10]+m_K_e[0][11]*err[11]+m_K_e[0][12]*err[12]+m_K_e[0][13]*err[13]+m_K_e[0][14]*err[14]+m_K_e[0][15]*err[15]);
    const double u_tx = -(m_K_e[1][0]*err[0]+m_K_e[1][1]*err[1]+m_K_e[1][2]*err[2]+m_K_e[1][3]*err[3]+m_K_e[1][4]*err[4]+m_K_e[1][5]*err[5]+m_K_e[1][6]*err[6]+m_K_e[1][7]*err[7]+m_K_e[1][8]*err[8]+m_K_e[1][9]*err[9]+m_K_e[1][10]*err[10]+m_K_e[1][11]*err[11]+m_K_e[1][12]*err[12]+m_K_e[1][13]*err[13]+m_K_e[1][14]*err[14]+m_K_e[1][15]*err[15]);
    const double u_ty = -(m_K_e[2][0]*err[0]+m_K_e[2][1]*err[1]+m_K_e[2][2]*err[2]+m_K_e[2][3]*err[3]+m_K_e[2][4]*err[4]+m_K_e[2][5]*err[5]+m_K_e[2][6]*err[6]+m_K_e[2][7]*err[7]+m_K_e[2][8]*err[8]+m_K_e[2][9]*err[9]+m_K_e[2][10]*err[10]+m_K_e[2][11]*err[11]+m_K_e[2][12]*err[12]+m_K_e[2][13]*err[13]+m_K_e[2][14]*err[14]+m_K_e[2][15]*err[15]);
    const double u_tz = -(m_K_e[3][0]*err[0]+m_K_e[3][1]*err[1]+m_K_e[3][2]*err[2]+m_K_e[3][3]*err[3]+m_K_e[3][4]*err[4]+m_K_e[3][5]*err[5]+m_K_e[3][6]*err[6]+m_K_e[3][7]*err[7]+m_K_e[3][8]*err[8]+m_K_e[3][9]*err[9]+m_K_e[3][10]*err[10]+m_K_e[3][11]*err[11]+m_K_e[3][12]*err[12]+m_K_e[3][13]*err[13]+m_K_e[3][14]*err[14]+m_K_e[3][15]*err[15]);
    const double Fc  = F_ff  + u_F;
    const double tcx = tff_x + u_tx;
    const double tcy = tff_y + u_ty;
    const double tcz = tff_z + u_tz;

    double T1 = (0.25)*Fc + (-0.35355339059327376/m_p.L)*tcx + (-0.35355339059327376/m_p.L)*tcy + (-0.25*m_p.kT/m_p.kQ)*tcz;
    double T2 = (0.25)*Fc + (0.35355339059327376/m_p.L)*tcx + (0.35355339059327376/m_p.L)*tcy + (-0.25*m_p.kT/m_p.kQ)*tcz;
    double T3 = (0.25)*Fc + (0.35355339059327376/m_p.L)*tcx + (-0.35355339059327376/m_p.L)*tcy + (0.25*m_p.kT/m_p.kQ)*tcz;
    double T4 = (0.25)*Fc + (-0.35355339059327376/m_p.L)*tcx + (0.35355339059327376/m_p.L)*tcy + (0.25*m_p.kT/m_p.kQ)*tcz;

    InputVec Tcmd{};
    T1=std::min(std::max(T1,m_p.T_min),m_p.T_max); Tcmd[0]=T1;
    T2=std::min(std::max(T2,m_p.T_min),m_p.T_max); Tcmd[1]=T2;
    T3=std::min(std::max(T3,m_p.T_min),m_p.T_max); Tcmd[2]=T3;
    T4=std::min(std::max(T4,m_p.T_min),m_p.T_max); Tcmd[3]=T4;
    return Tcmd;
}

} }  // namespace CDS::Dynamics
