/* dynamics_quadrotor_ff_lqr_01.hpp -- generated by dynamics_quadRotor_FFLQR01.ipynb.
 * Author: Diego Perazzolo. Do not edit by hand.
 */
#pragma once
#include <array>
#include <cstddef>
#ifdef JUST_TESTING_DYNAMICS
#include "test_core_defs.hpp"
#else
#include "core_defs.hpp"
#endif

namespace CDS { namespace Dynamics {

class QUADROTOR_FF_LQR_01 {
public:
    using StateVec = std::array<double, 17>;
    using InputVec = std::array<double, 4>;

    enum class StateName : std::size_t {
        X = 0,
        Y = 1,
        Z = 2,
        Qw = 3,
        Qx = 4,
        Qy = 5,
        Qz = 6,
        VX = 7,
        VY = 8,
        VZ = 9,
        WX = 10,
        WY = 11,
        WZ = 12,
        IntX = 13,
        IntY = 14,
        IntZ = 15,
        IntPsi = 16,
    };
    enum class ParamName : std::size_t {
        Mass = 0,
        Ix = 1,
        Iy = 2,
        Iz = 3,
        Gravity = 4,
        DragLat = 5,
        DragAx = 6,
        KThrust = 7,
        KTorque = 8,
        Arm = 9,
        IRotor = 10,
        ThrustMax = 11,
        ThrustMin = 12,
    };

    QUADROTOR_FF_LQR_01();
    InputVec ExecuteControl(const StateVec& s, const Reference_t& r) const;
    StateVec Dynamics(const StateVec& s, const InputVec& u,
                      const Reference_t& ref, const std::array<double, 3>& userF) const;
    static double GetState(const StateVec& s, StateName n);
    static void   SetState(StateVec& s, StateName n, double v);
    double GetParam(ParamName n) const;
    void   SetParam(ParamName n, double v);
    static constexpr std::size_t StateToIdx(StateName n) noexcept { return static_cast<std::size_t>(n); }

private:
    struct PhysicsParams {
            double m = 2.4;  // vehicle mass [kg]
            double Ix = 0.025;  // inertia x [kg m^2]
            double Iy = 0.025;  // inertia y [kg m^2]
            double Iz = 0.045;  // inertia z [kg m^2]
            double g = 9.81;  // gravity [m/s^2]
            double c = 0.2;  // lateral drag
            double cz = 0.3;  // axial drag
            double kT = 1e-05;  // thrust coeff kT
            double kQ = 1.6e-07;  // torque coeff kQ
            double L = 0.275;  // arm length [m]
            double Irot = 3e-05;  // rotor inertia
            double T_max = 36.0;  // per-rotor thrust max [N]
            double T_min = 0.0;  // per-rotor thrust min [N]
    };
    PhysicsParams m_p;
};

} }  // namespace CDS::Dynamics
